<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="api_tests.xsl" type="text/xsl" ?>
<unittest-results date_time = "2013-05-23 13:51:53" tests="886" failedtests="886" failures="886" time="25.005">
<test suite="SBML_l2v4" name="1" time="0.021"><failure message="sbml_test_suite.cpp(19) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 1))"/></test>
<test suite="SBML_l2v4" name="2" time="0.022"><failure message="sbml_test_suite.cpp(20) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 2))"/></test>
<test suite="SBML_l2v4" name="3" time="0.017"><failure message="sbml_test_suite.cpp(21) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 3))"/></test>
<test suite="SBML_l2v4" name="4" time="0.025"><failure message="sbml_test_suite.cpp(22) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 4))"/></test>
<test suite="SBML_l2v4" name="5" time="0.016"><failure message="sbml_test_suite.cpp(23) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 5))"/></test>
<test suite="SBML_l2v4" name="6" time="0.022"><failure message="sbml_test_suite.cpp(24) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 6))"/></test>
<test suite="SBML_l2v4" name="7" time="0.023"><failure message="sbml_test_suite.cpp(25) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 7))"/></test>
<test suite="SBML_l2v4" name="8" time="0.023"><failure message="sbml_test_suite.cpp(26) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 8))"/></test>
<test suite="SBML_l2v4" name="9" time="0.023"><failure message="sbml_test_suite.cpp(27) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 9))"/></test>
<test suite="SBML_l2v4" name="10" time="0.024"><failure message="sbml_test_suite.cpp(28) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 10))"/></test>
<test suite="SBML_l2v4" name="11" time="0.025"><failure message="sbml_test_suite.cpp(29) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 11))"/></test>
<test suite="SBML_l2v4" name="12" time="0.025"><failure message="sbml_test_suite.cpp(30) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 12))"/></test>
<test suite="SBML_l2v4" name="13" time="0.024"><failure message="sbml_test_suite.cpp(31) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 13))"/></test>
<test suite="SBML_l2v4" name="14" time="0.025"><failure message="sbml_test_suite.cpp(32) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 14))"/></test>
<test suite="SBML_l2v4" name="15" time="0.026"><failure message="sbml_test_suite.cpp(33) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 15))"/></test>
<test suite="SBML_l2v4" name="16" time="0.026"><failure message="sbml_test_suite.cpp(34) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 16))"/></test>
<test suite="SBML_l2v4" name="17" time="0.026"><failure message="sbml_test_suite.cpp(35) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 17))"/></test>
<test suite="SBML_l2v4" name="18" time="0.034"><failure message="sbml_test_suite.cpp(36) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 18))"/></test>
<test suite="SBML_l2v4" name="19" time="0.034"><failure message="sbml_test_suite.cpp(37) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 19))"/></test>
<test suite="SBML_l2v4" name="20" time="0.054"><failure message="sbml_test_suite.cpp(38) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 20))"/></test>
<test suite="SBML_l2v4" name="21" time="0.025"><failure message="sbml_test_suite.cpp(39) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 21))"/></test>
<test suite="SBML_l2v4" name="22" time="0.026"><failure message="sbml_test_suite.cpp(40) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 22))"/></test>
<test suite="SBML_l2v4" name="23" time="0.035"><failure message="sbml_test_suite.cpp(41) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 23))"/></test>
<test suite="SBML_l2v4" name="24" time="0.037"><failure message="sbml_test_suite.cpp(42) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 24))"/></test>
<test suite="SBML_l2v4" name="25" time="0.021"><failure message="sbml_test_suite.cpp(43) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 25))"/></test>
<test suite="SBML_l2v4" name="26" time="0.02"><failure message="sbml_test_suite.cpp(44) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 26))"/></test>
<test suite="SBML_l2v4" name="27" time="0.017"><failure message="sbml_test_suite.cpp(45) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 27))"/></test>
<test suite="SBML_l2v4" name="28" time="0.019"><failure message="sbml_test_suite.cpp(46) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 28))"/></test>
<test suite="SBML_l2v4" name="29" time="0.014"><failure message="sbml_test_suite.cpp(47) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 29))"/></test>
<test suite="SBML_l2v4" name="30" time="0.013"><failure message="sbml_test_suite.cpp(48) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 30))"/></test>
<test suite="SBML_l2v4" name="31" time="0.013"><failure message="sbml_test_suite.cpp(49) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 31))"/></test>
<test suite="SBML_l2v4" name="32" time="0.019"><failure message="sbml_test_suite.cpp(50) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 32))"/></test>
<test suite="SBML_l2v4" name="33" time="0.018"><failure message="sbml_test_suite.cpp(51) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 33))"/></test>
<test suite="SBML_l2v4" name="34" time="0.036"><failure message="sbml_test_suite.cpp(52) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 34))"/></test>
<test suite="SBML_l2v4" name="35" time="0.029"><failure message="sbml_test_suite.cpp(53) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 35))"/></test>
<test suite="SBML_l2v4" name="36" time="0.02"><failure message="sbml_test_suite.cpp(54) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 36))"/></test>
<test suite="SBML_l2v4" name="37" time="0.02"><failure message="sbml_test_suite.cpp(55) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 37))"/></test>
<test suite="SBML_l2v4" name="38" time="0.022"><failure message="sbml_test_suite.cpp(56) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 38))"/></test>
<test suite="SBML_l2v4" name="41" time="0.025"><failure message="sbml_test_suite.cpp(59) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 41))"/></test>
<test suite="SBML_l2v4" name="42" time="0.017"><failure message="sbml_test_suite.cpp(60) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 42))"/></test>
<test suite="SBML_l2v4" name="43" time="0.023"><failure message="sbml_test_suite.cpp(61) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 43))"/></test>
<test suite="SBML_l2v4" name="44" time="0.026"><failure message="sbml_test_suite.cpp(62) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 44))"/></test>
<test suite="SBML_l2v4" name="45" time="0.021"><failure message="sbml_test_suite.cpp(63) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 45))"/></test>
<test suite="SBML_l2v4" name="46" time="0.035"><failure message="sbml_test_suite.cpp(64) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 46))"/></test>
<test suite="SBML_l2v4" name="47" time="0.026"><failure message="sbml_test_suite.cpp(65) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 47))"/></test>
<test suite="SBML_l2v4" name="48" time="0.017"><failure message="sbml_test_suite.cpp(66) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 48))"/></test>
<test suite="SBML_l2v4" name="49" time="0.032"><failure message="sbml_test_suite.cpp(67) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 49))"/></test>
<test suite="SBML_l2v4" name="50" time="0.025"><failure message="sbml_test_suite.cpp(68) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 50))"/></test>
<test suite="SBML_l2v4" name="51" time="0.038"><failure message="sbml_test_suite.cpp(69) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 51))"/></test>
<test suite="SBML_l2v4" name="52" time="0.028"><failure message="sbml_test_suite.cpp(70) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 52))"/></test>
<test suite="SBML_l2v4" name="53" time="0.03"><failure message="sbml_test_suite.cpp(71) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 53))"/></test>
<test suite="SBML_l2v4" name="54" time="0.026"><failure message="sbml_test_suite.cpp(72) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 54))"/></test>
<test suite="SBML_l2v4" name="55" time="0.032"><failure message="sbml_test_suite.cpp(73) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 55))"/></test>
<test suite="SBML_l2v4" name="56" time="0.024"><failure message="sbml_test_suite.cpp(74) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 56))"/></test>
<test suite="SBML_l2v4" name="57" time="0.021"><failure message="sbml_test_suite.cpp(75) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 57))"/></test>
<test suite="SBML_l2v4" name="58" time="0.023"><failure message="sbml_test_suite.cpp(76) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 58))"/></test>
<test suite="SBML_l2v4" name="59" time="0.029"><failure message="sbml_test_suite.cpp(77) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 59))"/></test>
<test suite="SBML_l2v4" name="60" time="0.018"><failure message="sbml_test_suite.cpp(78) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 60))"/></test>
<test suite="SBML_l2v4" name="61" time="0.023"><failure message="sbml_test_suite.cpp(79) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 61))"/></test>
<test suite="SBML_l2v4" name="62" time="0.025"><failure message="sbml_test_suite.cpp(80) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 62))"/></test>
<test suite="SBML_l2v4" name="63" time="0.02"><failure message="sbml_test_suite.cpp(81) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 63))"/></test>
<test suite="SBML_l2v4" name="64" time="0.028"><failure message="sbml_test_suite.cpp(82) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 64))"/></test>
<test suite="SBML_l2v4" name="65" time="0.031"><failure message="sbml_test_suite.cpp(83) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 65))"/></test>
<test suite="SBML_l2v4" name="66" time="0.029"><failure message="sbml_test_suite.cpp(84) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 66))"/></test>
<test suite="SBML_l2v4" name="67" time="0.025"><failure message="sbml_test_suite.cpp(85) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 67))"/></test>
<test suite="SBML_l2v4" name="68" time="0.019"><failure message="sbml_test_suite.cpp(86) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 68))"/></test>
<test suite="SBML_l2v4" name="69" time="0.027"><failure message="sbml_test_suite.cpp(87) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 69))"/></test>
<test suite="SBML_l2v4" name="70" time="0.029"><failure message="sbml_test_suite.cpp(88) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 70))"/></test>
<test suite="SBML_l2v4" name="71" time="0.023"><failure message="sbml_test_suite.cpp(89) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 71))"/></test>
<test suite="SBML_l2v4" name="72" time="0.027"><failure message="sbml_test_suite.cpp(90) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 72))"/></test>
<test suite="SBML_l2v4" name="73" time="0.024"><failure message="sbml_test_suite.cpp(91) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 73))"/></test>
<test suite="SBML_l2v4" name="74" time="0.025"><failure message="sbml_test_suite.cpp(92) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 74))"/></test>
<test suite="SBML_l2v4" name="75" time="0.018"><failure message="sbml_test_suite.cpp(93) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 75))"/></test>
<test suite="SBML_l2v4" name="76" time="0.025"><failure message="sbml_test_suite.cpp(94) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 76))"/></test>
<test suite="SBML_l2v4" name="77" time="0.027"><failure message="sbml_test_suite.cpp(95) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 77))"/></test>
<test suite="SBML_l2v4" name="78" time="0.025"><failure message="sbml_test_suite.cpp(96) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 78))"/></test>
<test suite="SBML_l2v4" name="79" time="0.031"><failure message="sbml_test_suite.cpp(97) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 79))"/></test>
<test suite="SBML_l2v4" name="80" time="0.045"><failure message="sbml_test_suite.cpp(98) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 80))"/></test>
<test suite="SBML_l2v4" name="81" time="0.018"><failure message="sbml_test_suite.cpp(99) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 81))"/></test>
<test suite="SBML_l2v4" name="82" time="0.027"><failure message="sbml_test_suite.cpp(100) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 82))"/></test>
<test suite="SBML_l2v4" name="83" time="0.024"><failure message="sbml_test_suite.cpp(101) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 83))"/></test>
<test suite="SBML_l2v4" name="84" time="0.024"><failure message="sbml_test_suite.cpp(102) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 84))"/></test>
<test suite="SBML_l2v4" name="85" time="0.03"><failure message="sbml_test_suite.cpp(103) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 85))"/></test>
<test suite="SBML_l2v4" name="86" time="0.03"><failure message="sbml_test_suite.cpp(104) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 86))"/></test>
<test suite="SBML_l2v4" name="87" time="0.022"><failure message="sbml_test_suite.cpp(105) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 87))"/></test>
<test suite="SBML_l2v4" name="88" time="0.023"><failure message="sbml_test_suite.cpp(106) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 88))"/></test>
<test suite="SBML_l2v4" name="89" time="0.029"><failure message="sbml_test_suite.cpp(107) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 89))"/></test>
<test suite="SBML_l2v4" name="90" time="0.034"><failure message="sbml_test_suite.cpp(108) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 90))"/></test>
<test suite="SBML_l2v4" name="91" time="0.034"><failure message="sbml_test_suite.cpp(109) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 91))"/></test>
<test suite="SBML_l2v4" name="92" time="0.033"><failure message="sbml_test_suite.cpp(110) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 92))"/></test>
<test suite="SBML_l2v4" name="93" time="0.03"><failure message="sbml_test_suite.cpp(111) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 93))"/></test>
<test suite="SBML_l2v4" name="94" time="0.03"><failure message="sbml_test_suite.cpp(112) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 94))"/></test>
<test suite="SBML_l2v4" name="95" time="0.022"><failure message="sbml_test_suite.cpp(113) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 95))"/></test>
<test suite="SBML_l2v4" name="96" time="0.022"><failure message="sbml_test_suite.cpp(114) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 96))"/></test>
<test suite="SBML_l2v4" name="97" time="0.024"><failure message="sbml_test_suite.cpp(115) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 97))"/></test>
<test suite="SBML_l2v4" name="98" time="0.03"><failure message="sbml_test_suite.cpp(116) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 98))"/></test>
<test suite="SBML_l2v4" name="99" time="0.029"><failure message="sbml_test_suite.cpp(117) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 99))"/></test>
<test suite="SBML_l2v4" name="100" time="0.028"><failure message="sbml_test_suite.cpp(118) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 100))"/></test>
<test suite="SBML_l2v4" name="101" time="0.032"><failure message="sbml_test_suite.cpp(119) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 101))"/></test>
<test suite="SBML_l2v4" name="102" time="0.031"><failure message="sbml_test_suite.cpp(120) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 102))"/></test>
<test suite="SBML_l2v4" name="103" time="0.029"><failure message="sbml_test_suite.cpp(121) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 103))"/></test>
<test suite="SBML_l2v4" name="104" time="0.024"><failure message="sbml_test_suite.cpp(122) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 104))"/></test>
<test suite="SBML_l2v4" name="105" time="0.033"><failure message="sbml_test_suite.cpp(123) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 105))"/></test>
<test suite="SBML_l2v4" name="106" time="0.058"><failure message="sbml_test_suite.cpp(124) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 106))"/></test>
<test suite="SBML_l2v4" name="107" time="0.021"><failure message="sbml_test_suite.cpp(125) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 107))"/></test>
<test suite="SBML_l2v4" name="108" time="0.028"><failure message="sbml_test_suite.cpp(126) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 108))"/></test>
<test suite="SBML_l2v4" name="109" time="0.031"><failure message="sbml_test_suite.cpp(127) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 109))"/></test>
<test suite="SBML_l2v4" name="110" time="0.031"><failure message="sbml_test_suite.cpp(128) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 110))"/></test>
<test suite="SBML_l2v4" name="111" time="0.037"><failure message="sbml_test_suite.cpp(129) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 111))"/></test>
<test suite="SBML_l2v4" name="112" time="0.028"><failure message="sbml_test_suite.cpp(130) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 112))"/></test>
<test suite="SBML_l2v4" name="113" time="0.023"><failure message="sbml_test_suite.cpp(131) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 113))"/></test>
<test suite="SBML_l2v4" name="114" time="0.029"><failure message="sbml_test_suite.cpp(132) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 114))"/></test>
<test suite="SBML_l2v4" name="115" time="0.028"><failure message="sbml_test_suite.cpp(133) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 115))"/></test>
<test suite="SBML_l2v4" name="116" time="0.027"><failure message="sbml_test_suite.cpp(134) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 116))"/></test>
<test suite="SBML_l2v4" name="117" time="0.025"><failure message="sbml_test_suite.cpp(135) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 117))"/></test>
<test suite="SBML_l2v4" name="118" time="0.029"><failure message="sbml_test_suite.cpp(136) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 118))"/></test>
<test suite="SBML_l2v4" name="119" time="0.046"><failure message="sbml_test_suite.cpp(137) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 119))"/></test>
<test suite="SBML_l2v4" name="120" time="0.036"><failure message="sbml_test_suite.cpp(138) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 120))"/></test>
<test suite="SBML_l2v4" name="121" time="0.034"><failure message="sbml_test_suite.cpp(139) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 121))"/></test>
<test suite="SBML_l2v4" name="122" time="0.028"><failure message="sbml_test_suite.cpp(140) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 122))"/></test>
<test suite="SBML_l2v4" name="123" time="0.035"><failure message="sbml_test_suite.cpp(141) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 123))"/></test>
<test suite="SBML_l2v4" name="124" time="0.034"><failure message="sbml_test_suite.cpp(142) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 124))"/></test>
<test suite="SBML_l2v4" name="125" time="0.026"><failure message="sbml_test_suite.cpp(143) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 125))"/></test>
<test suite="SBML_l2v4" name="126" time="0.027"><failure message="sbml_test_suite.cpp(144) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 126))"/></test>
<test suite="SBML_l2v4" name="127" time="0.029"><failure message="sbml_test_suite.cpp(145) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 127))"/></test>
<test suite="SBML_l2v4" name="128" time="0.03"><failure message="sbml_test_suite.cpp(146) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 128))"/></test>
<test suite="SBML_l2v4" name="129" time="0.023"><failure message="sbml_test_suite.cpp(147) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 129))"/></test>
<test suite="SBML_l2v4" name="130" time="0.032"><failure message="sbml_test_suite.cpp(148) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 130))"/></test>
<test suite="SBML_l2v4" name="131" time="0.037"><failure message="sbml_test_suite.cpp(149) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 131))"/></test>
<test suite="SBML_l2v4" name="132" time="0.026"><failure message="sbml_test_suite.cpp(150) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 132))"/></test>
<test suite="SBML_l2v4" name="133" time="0.028"><failure message="sbml_test_suite.cpp(151) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 133))"/></test>
<test suite="SBML_l2v4" name="134" time="0.047"><failure message="sbml_test_suite.cpp(152) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 134))"/></test>
<test suite="SBML_l2v4" name="135" time="0.021"><failure message="sbml_test_suite.cpp(153) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 135))"/></test>
<test suite="SBML_l2v4" name="136" time="0.019"><failure message="sbml_test_suite.cpp(154) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 136))"/></test>
<test suite="SBML_l2v4" name="137" time="0.02"><failure message="sbml_test_suite.cpp(155) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 137))"/></test>
<test suite="SBML_l2v4" name="138" time="0.02"><failure message="sbml_test_suite.cpp(156) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 138))"/></test>
<test suite="SBML_l2v4" name="139" time="0.025"><failure message="sbml_test_suite.cpp(157) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 139))"/></test>
<test suite="SBML_l2v4" name="140" time="0.019"><failure message="sbml_test_suite.cpp(158) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 140))"/></test>
<test suite="SBML_l2v4" name="141" time="0.022"><failure message="sbml_test_suite.cpp(159) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 141))"/></test>
<test suite="SBML_l2v4" name="142" time="0.028"><failure message="sbml_test_suite.cpp(160) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 142))"/></test>
<test suite="SBML_l2v4" name="143" time="0.026"><failure message="sbml_test_suite.cpp(161) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 143))"/></test>
<test suite="SBML_l2v4" name="144" time="0.027"><failure message="sbml_test_suite.cpp(162) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 144))"/></test>
<test suite="SBML_l2v4" name="145" time="0.027"><failure message="sbml_test_suite.cpp(163) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 145))"/></test>
<test suite="SBML_l2v4" name="146" time="0.027"><failure message="sbml_test_suite.cpp(164) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 146))"/></test>
<test suite="SBML_l2v4" name="147" time="0.026"><failure message="sbml_test_suite.cpp(165) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 147))"/></test>
<test suite="SBML_l2v4" name="148" time="0.018"><failure message="sbml_test_suite.cpp(166) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 148))"/></test>
<test suite="SBML_l2v4" name="149" time="0.02"><failure message="sbml_test_suite.cpp(167) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 149))"/></test>
<test suite="SBML_l2v4" name="150" time="0.027"><failure message="sbml_test_suite.cpp(168) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 150))"/></test>
<test suite="SBML_l2v4" name="151" time="0.028"><failure message="sbml_test_suite.cpp(169) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 151))"/></test>
<test suite="SBML_l2v4" name="152" time="0.022"><failure message="sbml_test_suite.cpp(170) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 152))"/></test>
<test suite="SBML_l2v4" name="153" time="0.027"><failure message="sbml_test_suite.cpp(171) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 153))"/></test>
<test suite="SBML_l2v4" name="154" time="0.025"><failure message="sbml_test_suite.cpp(172) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 154))"/></test>
<test suite="SBML_l2v4" name="155" time="0.061"><failure message="sbml_test_suite.cpp(173) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 155))"/></test>
<test suite="SBML_l2v4" name="156" time="0.023"><failure message="sbml_test_suite.cpp(174) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 156))"/></test>
<test suite="SBML_l2v4" name="157" time="0.03"><failure message="sbml_test_suite.cpp(175) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 157))"/></test>
<test suite="SBML_l2v4" name="158" time="0.026"><failure message="sbml_test_suite.cpp(176) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 158))"/></test>
<test suite="SBML_l2v4" name="159" time="0.03"><failure message="sbml_test_suite.cpp(177) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 159))"/></test>
<test suite="SBML_l2v4" name="160" time="0.024"><failure message="sbml_test_suite.cpp(178) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 160))"/></test>
<test suite="SBML_l2v4" name="161" time="0.018"><failure message="sbml_test_suite.cpp(179) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 161))"/></test>
<test suite="SBML_l2v4" name="162" time="0.025"><failure message="sbml_test_suite.cpp(180) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 162))"/></test>
<test suite="SBML_l2v4" name="163" time="0.021"><failure message="sbml_test_suite.cpp(181) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 163))"/></test>
<test suite="SBML_l2v4" name="164" time="0.021"><failure message="sbml_test_suite.cpp(182) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 164))"/></test>
<test suite="SBML_l2v4" name="165" time="0.026"><failure message="sbml_test_suite.cpp(183) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 165))"/></test>
<test suite="SBML_l2v4" name="166" time="0.034"><failure message="sbml_test_suite.cpp(184) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 166))"/></test>
<test suite="SBML_l2v4" name="167" time="0.036"><failure message="sbml_test_suite.cpp(185) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 167))"/></test>
<test suite="SBML_l2v4" name="168" time="0.033"><failure message="sbml_test_suite.cpp(186) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 168))"/></test>
<test suite="SBML_l2v4" name="169" time="0.031"><failure message="sbml_test_suite.cpp(187) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 169))"/></test>
<test suite="SBML_l2v4" name="170" time="0.029"><failure message="sbml_test_suite.cpp(188) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 170))"/></test>
<test suite="SBML_l2v4" name="171" time="0.021"><failure message="sbml_test_suite.cpp(189) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 171))"/></test>
<test suite="SBML_l2v4" name="172" time="0.023"><failure message="sbml_test_suite.cpp(190) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 172))"/></test>
<test suite="SBML_l2v4" name="173" time="0.053"><failure message="sbml_test_suite.cpp(191) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 173))"/></test>
<test suite="SBML_l2v4" name="174" time="0.012"><failure message="sbml_test_suite.cpp(192) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 174))"/></test>
<test suite="SBML_l2v4" name="175" time="0.012"><failure message="sbml_test_suite.cpp(193) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 175))"/></test>
<test suite="SBML_l2v4" name="176" time="0.019"><failure message="sbml_test_suite.cpp(194) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 176))"/></test>
<test suite="SBML_l2v4" name="177" time="0.018"><failure message="sbml_test_suite.cpp(195) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 177))"/></test>
<test suite="SBML_l2v4" name="178" time="0.038"><failure message="sbml_test_suite.cpp(196) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 178))"/></test>
<test suite="SBML_l2v4" name="179" time="0.037"><failure message="sbml_test_suite.cpp(197) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 179))"/></test>
<test suite="SBML_l2v4" name="180" time="0.019"><failure message="sbml_test_suite.cpp(198) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 180))"/></test>
<test suite="SBML_l2v4" name="181" time="0.021"><failure message="sbml_test_suite.cpp(199) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 181))"/></test>
<test suite="SBML_l2v4" name="183" time="0.024"><failure message="sbml_test_suite.cpp(201) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 183))"/></test>
<test suite="SBML_l2v4" name="185" time="0.024"><failure message="sbml_test_suite.cpp(203) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 185))"/></test>
<test suite="SBML_l2v4" name="186" time="0.025"><failure message="sbml_test_suite.cpp(204) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 186))"/></test>
<test suite="SBML_l2v4" name="187" time="0.025"><failure message="sbml_test_suite.cpp(205) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 187))"/></test>
<test suite="SBML_l2v4" name="188" time="0.028"><failure message="sbml_test_suite.cpp(206) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 188))"/></test>
<test suite="SBML_l2v4" name="189" time="0.026"><failure message="sbml_test_suite.cpp(207) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 189))"/></test>
<test suite="SBML_l2v4" name="190" time="0.019"><failure message="sbml_test_suite.cpp(208) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 190))"/></test>
<test suite="SBML_l2v4" name="191" time="0.037"><failure message="sbml_test_suite.cpp(209) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 191))"/></test>
<test suite="SBML_l2v4" name="192" time="0.027"><failure message="sbml_test_suite.cpp(210) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 192))"/></test>
<test suite="SBML_l2v4" name="193" time="0.028"><failure message="sbml_test_suite.cpp(211) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 193))"/></test>
<test suite="SBML_l2v4" name="194" time="0.026"><failure message="sbml_test_suite.cpp(212) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 194))"/></test>
<test suite="SBML_l2v4" name="195" time="0.021"><failure message="sbml_test_suite.cpp(213) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 195))"/></test>
<test suite="SBML_l2v4" name="196" time="0.022"><failure message="sbml_test_suite.cpp(214) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 196))"/></test>
<test suite="SBML_l2v4" name="197" time="0.024"><failure message="sbml_test_suite.cpp(215) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 197))"/></test>
<test suite="SBML_l2v4" name="198" time="0.03"><failure message="sbml_test_suite.cpp(216) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 198))"/></test>
<test suite="SBML_l2v4" name="199" time="0.025"><failure message="sbml_test_suite.cpp(217) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 199))"/></test>
<test suite="SBML_l2v4" name="200" time="0.027"><failure message="sbml_test_suite.cpp(218) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 200))"/></test>
<test suite="SBML_l2v4" name="201" time="0.051"><failure message="sbml_test_suite.cpp(219) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 201))"/></test>
<test suite="SBML_l2v4" name="202" time="0.017"><failure message="sbml_test_suite.cpp(220) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 202))"/></test>
<test suite="SBML_l2v4" name="203" time="0.025"><failure message="sbml_test_suite.cpp(221) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 203))"/></test>
<test suite="SBML_l2v4" name="204" time="0.026"><failure message="sbml_test_suite.cpp(222) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 204))"/></test>
<test suite="SBML_l2v4" name="205" time="0.018"><failure message="sbml_test_suite.cpp(223) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 205))"/></test>
<test suite="SBML_l2v4" name="206" time="0.024"><failure message="sbml_test_suite.cpp(224) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 206))"/></test>
<test suite="SBML_l2v4" name="207" time="0.027"><failure message="sbml_test_suite.cpp(225) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 207))"/></test>
<test suite="SBML_l2v4" name="208" time="0.017"><failure message="sbml_test_suite.cpp(226) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 208))"/></test>
<test suite="SBML_l2v4" name="209" time="0.023"><failure message="sbml_test_suite.cpp(227) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 209))"/></test>
<test suite="SBML_l2v4" name="210" time="0.035"><failure message="sbml_test_suite.cpp(228) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 210))"/></test>
<test suite="SBML_l2v4" name="211" time="0.017"><failure message="sbml_test_suite.cpp(229) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 211))"/></test>
<test suite="SBML_l2v4" name="212" time="0.019"><failure message="sbml_test_suite.cpp(230) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 212))"/></test>
<test suite="SBML_l2v4" name="213" time="0.019"><failure message="sbml_test_suite.cpp(231) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 213))"/></test>
<test suite="SBML_l2v4" name="214" time="0.026"><failure message="sbml_test_suite.cpp(232) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 214))"/></test>
<test suite="SBML_l2v4" name="215" time="0.024"><failure message="sbml_test_suite.cpp(233) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 215))"/></test>
<test suite="SBML_l2v4" name="216" time="0.029"><failure message="sbml_test_suite.cpp(234) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 216))"/></test>
<test suite="SBML_l2v4" name="217" time="0.025"><failure message="sbml_test_suite.cpp(235) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 217))"/></test>
<test suite="SBML_l2v4" name="218" time="0.026"><failure message="sbml_test_suite.cpp(236) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 218))"/></test>
<test suite="SBML_l2v4" name="219" time="0.029"><failure message="sbml_test_suite.cpp(237) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 219))"/></test>
<test suite="SBML_l2v4" name="220" time="0.03"><failure message="sbml_test_suite.cpp(238) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 220))"/></test>
<test suite="SBML_l2v4" name="221" time="0.032"><failure message="sbml_test_suite.cpp(239) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 221))"/></test>
<test suite="SBML_l2v4" name="222" time="0.028"><failure message="sbml_test_suite.cpp(240) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 222))"/></test>
<test suite="SBML_l2v4" name="223" time="0.019"><failure message="sbml_test_suite.cpp(241) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 223))"/></test>
<test suite="SBML_l2v4" name="224" time="0.025"><failure message="sbml_test_suite.cpp(242) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 224))"/></test>
<test suite="SBML_l2v4" name="225" time="0.03"><failure message="sbml_test_suite.cpp(243) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 225))"/></test>
<test suite="SBML_l2v4" name="226" time="0.018"><failure message="sbml_test_suite.cpp(244) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 226))"/></test>
<test suite="SBML_l2v4" name="227" time="0.018"><failure message="sbml_test_suite.cpp(245) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 227))"/></test>
<test suite="SBML_l2v4" name="228" time="0.017"><failure message="sbml_test_suite.cpp(246) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 228))"/></test>
<test suite="SBML_l2v4" name="229" time="0.026"><failure message="sbml_test_suite.cpp(247) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 229))"/></test>
<test suite="SBML_l2v4" name="230" time="0.026"><failure message="sbml_test_suite.cpp(248) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 230))"/></test>
<test suite="SBML_l2v4" name="231" time="0.032"><failure message="sbml_test_suite.cpp(249) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 231))"/></test>
<test suite="SBML_l2v4" name="232" time="0.023"><failure message="sbml_test_suite.cpp(250) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 232))"/></test>
<test suite="SBML_l2v4" name="233" time="0.027"><failure message="sbml_test_suite.cpp(251) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 233))"/></test>
<test suite="SBML_l2v4" name="234" time="0.026"><failure message="sbml_test_suite.cpp(252) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 234))"/></test>
<test suite="SBML_l2v4" name="235" time="0.026"><failure message="sbml_test_suite.cpp(253) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 235))"/></test>
<test suite="SBML_l2v4" name="236" time="0.027"><failure message="sbml_test_suite.cpp(254) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 236))"/></test>
<test suite="SBML_l2v4" name="237" time="0.024"><failure message="sbml_test_suite.cpp(255) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 237))"/></test>
<test suite="SBML_l2v4" name="238" time="0.017"><failure message="sbml_test_suite.cpp(256) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 238))"/></test>
<test suite="SBML_l2v4" name="239" time="0.018"><failure message="sbml_test_suite.cpp(257) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 239))"/></test>
<test suite="SBML_l2v4" name="240" time="0.026"><failure message="sbml_test_suite.cpp(258) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 240))"/></test>
<test suite="SBML_l2v4" name="241" time="0.023"><failure message="sbml_test_suite.cpp(259) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 241))"/></test>
<test suite="SBML_l2v4" name="242" time="0.023"><failure message="sbml_test_suite.cpp(260) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 242))"/></test>
<test suite="SBML_l2v4" name="243" time="0.024"><failure message="sbml_test_suite.cpp(261) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 243))"/></test>
<test suite="SBML_l2v4" name="244" time="0.025"><failure message="sbml_test_suite.cpp(262) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 244))"/></test>
<test suite="SBML_l2v4" name="245" time="0.023"><failure message="sbml_test_suite.cpp(263) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 245))"/></test>
<test suite="SBML_l2v4" name="246" time="0.025"><failure message="sbml_test_suite.cpp(264) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 246))"/></test>
<test suite="SBML_l2v4" name="247" time="0.026"><failure message="sbml_test_suite.cpp(265) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 247))"/></test>
<test suite="SBML_l2v4" name="248" time="0.02"><failure message="sbml_test_suite.cpp(266) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 248))"/></test>
<test suite="SBML_l2v4" name="249" time="0.027"><failure message="sbml_test_suite.cpp(267) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 249))"/></test>
<test suite="SBML_l2v4" name="250" time="0.028"><failure message="sbml_test_suite.cpp(268) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 250))"/></test>
<test suite="SBML_l2v4" name="251" time="0.02"><failure message="sbml_test_suite.cpp(269) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 251))"/></test>
<test suite="SBML_l2v4" name="252" time="0.026"><failure message="sbml_test_suite.cpp(270) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 252))"/></test>
<test suite="SBML_l2v4" name="253" time="0.036"><failure message="sbml_test_suite.cpp(271) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 253))"/></test>
<test suite="SBML_l2v4" name="254" time="0.024"><failure message="sbml_test_suite.cpp(272) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 254))"/></test>
<test suite="SBML_l2v4" name="255" time="0.026"><failure message="sbml_test_suite.cpp(273) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 255))"/></test>
<test suite="SBML_l2v4" name="256" time="0.027"><failure message="sbml_test_suite.cpp(274) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 256))"/></test>
<test suite="SBML_l2v4" name="257" time="0.019"><failure message="sbml_test_suite.cpp(275) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 257))"/></test>
<test suite="SBML_l2v4" name="258" time="0.028"><failure message="sbml_test_suite.cpp(276) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 258))"/></test>
<test suite="SBML_l2v4" name="259" time="0.029"><failure message="sbml_test_suite.cpp(277) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 259))"/></test>
<test suite="SBML_l2v4" name="260" time="0.025"><failure message="sbml_test_suite.cpp(278) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 260))"/></test>
<test suite="SBML_l2v4" name="261" time="0.029"><failure message="sbml_test_suite.cpp(279) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 261))"/></test>
<test suite="SBML_l2v4" name="262" time="0.022"><failure message="sbml_test_suite.cpp(280) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 262))"/></test>
<test suite="SBML_l2v4" name="263" time="0.027"><failure message="sbml_test_suite.cpp(281) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 263))"/></test>
<test suite="SBML_l2v4" name="264" time="0.045"><failure message="sbml_test_suite.cpp(282) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 264))"/></test>
<test suite="SBML_l2v4" name="265" time="0.031"><failure message="sbml_test_suite.cpp(283) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 265))"/></test>
<test suite="SBML_l2v4" name="266" time="0.029"><failure message="sbml_test_suite.cpp(284) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 266))"/></test>
<test suite="SBML_l2v4" name="267" time="0.034"><failure message="sbml_test_suite.cpp(285) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 267))"/></test>
<test suite="SBML_l2v4" name="268" time="0.025"><failure message="sbml_test_suite.cpp(286) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 268))"/></test>
<test suite="SBML_l2v4" name="269" time="0.026"><failure message="sbml_test_suite.cpp(287) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 269))"/></test>
<test suite="SBML_l2v4" name="270" time="0.044"><failure message="sbml_test_suite.cpp(288) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 270))"/></test>
<test suite="SBML_l2v4" name="271" time="0.02"><failure message="sbml_test_suite.cpp(289) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 271))"/></test>
<test suite="SBML_l2v4" name="272" time="0.03"><failure message="sbml_test_suite.cpp(290) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 272))"/></test>
<test suite="SBML_l2v4" name="273" time="0.033"><failure message="sbml_test_suite.cpp(291) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 273))"/></test>
<test suite="SBML_l2v4" name="274" time="0.034"><failure message="sbml_test_suite.cpp(292) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 274))"/></test>
<test suite="SBML_l2v4" name="275" time="0.023"><failure message="sbml_test_suite.cpp(293) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 275))"/></test>
<test suite="SBML_l2v4" name="276" time="0.035"><failure message="sbml_test_suite.cpp(294) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 276))"/></test>
<test suite="SBML_l2v4" name="277" time="0.029"><failure message="sbml_test_suite.cpp(295) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 277))"/></test>
<test suite="SBML_l2v4" name="278" time="0.032"><failure message="sbml_test_suite.cpp(296) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 278))"/></test>
<test suite="SBML_l2v4" name="279" time="0.033"><failure message="sbml_test_suite.cpp(297) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 279))"/></test>
<test suite="SBML_l2v4" name="280" time="0.022"><failure message="sbml_test_suite.cpp(298) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 280))"/></test>
<test suite="SBML_l2v4" name="281" time="0.022"><failure message="sbml_test_suite.cpp(299) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 281))"/></test>
<test suite="SBML_l2v4" name="282" time="0.028"><failure message="sbml_test_suite.cpp(300) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 282))"/></test>
<test suite="SBML_l2v4" name="283" time="0.03"><failure message="sbml_test_suite.cpp(301) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 283))"/></test>
<test suite="SBML_l2v4" name="284" time="0.03"><failure message="sbml_test_suite.cpp(302) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 284))"/></test>
<test suite="SBML_l2v4" name="285" time="0.032"><failure message="sbml_test_suite.cpp(303) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 285))"/></test>
<test suite="SBML_l2v4" name="286" time="0.037"><failure message="sbml_test_suite.cpp(304) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 286))"/></test>
<test suite="SBML_l2v4" name="287" time="0.038"><failure message="sbml_test_suite.cpp(305) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 287))"/></test>
<test suite="SBML_l2v4" name="288" time="0.03"><failure message="sbml_test_suite.cpp(306) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 288))"/></test>
<test suite="SBML_l2v4" name="289" time="0.03"><failure message="sbml_test_suite.cpp(307) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 289))"/></test>
<test suite="SBML_l2v4" name="290" time="0.031"><failure message="sbml_test_suite.cpp(308) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 290))"/></test>
<test suite="SBML_l2v4" name="291" time="0.037"><failure message="sbml_test_suite.cpp(309) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 291))"/></test>
<test suite="SBML_l2v4" name="292" time="0.036"><failure message="sbml_test_suite.cpp(310) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 292))"/></test>
<test suite="SBML_l2v4" name="293" time="0.029"><failure message="sbml_test_suite.cpp(311) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 293))"/></test>
<test suite="SBML_l2v4" name="294" time="0.029"><failure message="sbml_test_suite.cpp(312) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 294))"/></test>
<test suite="SBML_l2v4" name="295" time="0.022"><failure message="sbml_test_suite.cpp(313) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 295))"/></test>
<test suite="SBML_l2v4" name="296" time="0.03"><failure message="sbml_test_suite.cpp(314) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 296))"/></test>
<test suite="SBML_l2v4" name="297" time="0.024"><failure message="sbml_test_suite.cpp(315) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 297))"/></test>
<test suite="SBML_l2v4" name="298" time="0.022"><failure message="sbml_test_suite.cpp(316) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 298))"/></test>
<test suite="SBML_l2v4" name="299" time="0.029"><failure message="sbml_test_suite.cpp(317) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 299))"/></test>
<test suite="SBML_l2v4" name="300" time="0.028"><failure message="sbml_test_suite.cpp(318) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 300))"/></test>
<test suite="SBML_l2v4" name="301" time="0.028"><failure message="sbml_test_suite.cpp(319) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 301))"/></test>
<test suite="SBML_l2v4" name="302" time="0.029"><failure message="sbml_test_suite.cpp(320) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 302))"/></test>
<test suite="SBML_l2v4" name="303" time="0.022"><failure message="sbml_test_suite.cpp(321) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 303))"/></test>
<test suite="SBML_l2v4" name="304" time="0.023"><failure message="sbml_test_suite.cpp(322) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 304))"/></test>
<test suite="SBML_l2v4" name="305" time="0.021"><failure message="sbml_test_suite.cpp(323) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 305))"/></test>
<test suite="SBML_l2v4" name="306" time="0.028"><failure message="sbml_test_suite.cpp(324) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 306))"/></test>
<test suite="SBML_l2v4" name="307" time="0.029"><failure message="sbml_test_suite.cpp(325) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 307))"/></test>
<test suite="SBML_l2v4" name="308" time="0.028"><failure message="sbml_test_suite.cpp(326) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 308))"/></test>
<test suite="SBML_l2v4" name="309" time="0.022"><failure message="sbml_test_suite.cpp(327) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 309))"/></test>
<test suite="SBML_l2v4" name="310" time="0.022"><failure message="sbml_test_suite.cpp(328) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 310))"/></test>
<test suite="SBML_l2v4" name="311" time="0.022"><failure message="sbml_test_suite.cpp(329) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 311))"/></test>
<test suite="SBML_l2v4" name="312" time="0.024"><failure message="sbml_test_suite.cpp(330) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 312))"/></test>
<test suite="SBML_l2v4" name="313" time="0.029"><failure message="sbml_test_suite.cpp(331) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 313))"/></test>
<test suite="SBML_l2v4" name="314" time="0.03"><failure message="sbml_test_suite.cpp(332) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 314))"/></test>
<test suite="SBML_l2v4" name="315" time="0.031"><failure message="sbml_test_suite.cpp(333) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 315))"/></test>
<test suite="SBML_l2v4" name="316" time="0.033"><failure message="sbml_test_suite.cpp(334) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 316))"/></test>
<test suite="SBML_l2v4" name="317" time="0.033"><failure message="sbml_test_suite.cpp(335) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 317))"/></test>
<test suite="SBML_l2v4" name="318" time="0.03"><failure message="sbml_test_suite.cpp(336) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 318))"/></test>
<test suite="SBML_l2v4" name="319" time="0.021"><failure message="sbml_test_suite.cpp(337) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 319))"/></test>
<test suite="SBML_l2v4" name="320" time="0.022"><failure message="sbml_test_suite.cpp(338) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 320))"/></test>
<test suite="SBML_l2v4" name="321" time="0.021"><failure message="sbml_test_suite.cpp(339) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 321))"/></test>
<test suite="SBML_l2v4" name="322" time="0.028"><failure message="sbml_test_suite.cpp(340) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 322))"/></test>
<test suite="SBML_l2v4" name="323" time="0.027"><failure message="sbml_test_suite.cpp(341) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 323))"/></test>
<test suite="SBML_l2v4" name="324" time="0.026"><failure message="sbml_test_suite.cpp(342) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 324))"/></test>
<test suite="SBML_l2v4" name="325" time="0.025"><failure message="sbml_test_suite.cpp(343) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 325))"/></test>
<test suite="SBML_l2v4" name="326" time="0.026"><failure message="sbml_test_suite.cpp(344) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 326))"/></test>
<test suite="SBML_l2v4" name="327" time="0.027"><failure message="sbml_test_suite.cpp(345) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 327))"/></test>
<test suite="SBML_l2v4" name="328" time="0.025"><failure message="sbml_test_suite.cpp(346) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 328))"/></test>
<test suite="SBML_l2v4" name="329" time="0.022"><failure message="sbml_test_suite.cpp(347) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 329))"/></test>
<test suite="SBML_l2v4" name="330" time="0.029"><failure message="sbml_test_suite.cpp(348) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 330))"/></test>
<test suite="SBML_l2v4" name="331" time="0.022"><failure message="sbml_test_suite.cpp(349) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 331))"/></test>
<test suite="SBML_l2v4" name="332" time="0.026"><failure message="sbml_test_suite.cpp(350) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 332))"/></test>
<test suite="SBML_l2v4" name="333" time="0.026"><failure message="sbml_test_suite.cpp(351) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 333))"/></test>
<test suite="SBML_l2v4" name="334" time="0.024"><failure message="sbml_test_suite.cpp(352) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 334))"/></test>
<test suite="SBML_l2v4" name="335" time="0.023"><failure message="sbml_test_suite.cpp(353) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 335))"/></test>
<test suite="SBML_l2v4" name="336" time="0.023"><failure message="sbml_test_suite.cpp(354) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 336))"/></test>
<test suite="SBML_l2v4" name="337" time="0.022"><failure message="sbml_test_suite.cpp(355) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 337))"/></test>
<test suite="SBML_l2v4" name="338" time="0.027"><failure message="sbml_test_suite.cpp(356) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 338))"/></test>
<test suite="SBML_l2v4" name="339" time="0.028"><failure message="sbml_test_suite.cpp(357) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 339))"/></test>
<test suite="SBML_l2v4" name="340" time="0.029"><failure message="sbml_test_suite.cpp(358) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 340))"/></test>
<test suite="SBML_l2v4" name="341" time="0.03"><failure message="sbml_test_suite.cpp(359) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 341))"/></test>
<test suite="SBML_l2v4" name="342" time="0.03"><failure message="sbml_test_suite.cpp(360) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 342))"/></test>
<test suite="SBML_l2v4" name="343" time="0.024"><failure message="sbml_test_suite.cpp(361) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 343))"/></test>
<test suite="SBML_l2v4" name="344" time="0.026"><failure message="sbml_test_suite.cpp(362) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 344))"/></test>
<test suite="SBML_l2v4" name="345" time="0.024"><failure message="sbml_test_suite.cpp(363) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 345))"/></test>
<test suite="SBML_l2v4" name="346" time="0.026"><failure message="sbml_test_suite.cpp(364) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 346))"/></test>
<test suite="SBML_l2v4" name="347" time="0.03"><failure message="sbml_test_suite.cpp(365) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 347))"/></test>
<test suite="SBML_l2v4" name="348" time="0.03"><failure message="sbml_test_suite.cpp(366) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 348))"/></test>
<test suite="SBML_l2v4" name="349" time="0.035"><failure message="sbml_test_suite.cpp(367) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 349))"/></test>
<test suite="SBML_l2v4" name="350" time="0.029"><failure message="sbml_test_suite.cpp(368) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 350))"/></test>
<test suite="SBML_l2v4" name="351" time="0.033"><failure message="sbml_test_suite.cpp(369) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 351))"/></test>
<test suite="SBML_l2v4" name="352" time="0.037"><failure message="sbml_test_suite.cpp(370) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 352))"/></test>
<test suite="SBML_l2v4" name="353" time="0.031"><failure message="sbml_test_suite.cpp(371) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 353))"/></test>
<test suite="SBML_l2v4" name="354" time="0.035"><failure message="sbml_test_suite.cpp(372) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 354))"/></test>
<test suite="SBML_l2v4" name="355" time="0.033"><failure message="sbml_test_suite.cpp(373) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 355))"/></test>
<test suite="SBML_l2v4" name="356" time="0.044"><failure message="sbml_test_suite.cpp(374) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 356))"/></test>
<test suite="SBML_l2v4" name="357" time="0.044"><failure message="sbml_test_suite.cpp(375) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 357))"/></test>
<test suite="SBML_l2v4" name="358" time="0.041"><failure message="sbml_test_suite.cpp(376) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 358))"/></test>
<test suite="SBML_l2v4" name="359" time="0.039"><failure message="sbml_test_suite.cpp(377) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 359))"/></test>
<test suite="SBML_l2v4" name="360" time="0.03"><failure message="sbml_test_suite.cpp(378) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 360))"/></test>
<test suite="SBML_l2v4" name="361" time="0.029"><failure message="sbml_test_suite.cpp(379) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 361))"/></test>
<test suite="SBML_l2v4" name="362" time="0.027"><failure message="sbml_test_suite.cpp(380) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 362))"/></test>
<test suite="SBML_l2v4" name="363" time="0.034"><failure message="sbml_test_suite.cpp(381) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 363))"/></test>
<test suite="SBML_l2v4" name="364" time="0.034"><failure message="sbml_test_suite.cpp(382) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 364))"/></test>
<test suite="SBML_l2v4" name="365" time="0.031"><failure message="sbml_test_suite.cpp(383) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 365))"/></test>
<test suite="SBML_l2v4" name="366" time="0.028"><failure message="sbml_test_suite.cpp(384) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 366))"/></test>
<test suite="SBML_l2v4" name="367" time="0.029"><failure message="sbml_test_suite.cpp(385) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 367))"/></test>
<test suite="SBML_l2v4" name="368" time="0.033"><failure message="sbml_test_suite.cpp(386) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 368))"/></test>
<test suite="SBML_l2v4" name="369" time="0.03"><failure message="sbml_test_suite.cpp(387) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 369))"/></test>
<test suite="SBML_l2v4" name="370" time="0.033"><failure message="sbml_test_suite.cpp(388) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 370))"/></test>
<test suite="SBML_l2v4" name="371" time="0.031"><failure message="sbml_test_suite.cpp(389) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 371))"/></test>
<test suite="SBML_l2v4" name="372" time="0.03"><failure message="sbml_test_suite.cpp(390) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 372))"/></test>
<test suite="SBML_l2v4" name="373" time="0.037"><failure message="sbml_test_suite.cpp(391) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 373))"/></test>
<test suite="SBML_l2v4" name="374" time="0.033"><failure message="sbml_test_suite.cpp(392) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 374))"/></test>
<test suite="SBML_l2v4" name="375" time="0.03"><failure message="sbml_test_suite.cpp(393) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 375))"/></test>
<test suite="SBML_l2v4" name="376" time="0.027"><failure message="sbml_test_suite.cpp(394) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 376))"/></test>
<test suite="SBML_l2v4" name="377" time="0.028"><failure message="sbml_test_suite.cpp(395) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 377))"/></test>
<test suite="SBML_l2v4" name="378" time="0.034"><failure message="sbml_test_suite.cpp(396) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 378))"/></test>
<test suite="SBML_l2v4" name="379" time="0.031"><failure message="sbml_test_suite.cpp(397) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 379))"/></test>
<test suite="SBML_l2v4" name="380" time="0.034"><failure message="sbml_test_suite.cpp(398) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 380))"/></test>
<test suite="SBML_l2v4" name="381" time="0.03"><failure message="sbml_test_suite.cpp(399) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 381))"/></test>
<test suite="SBML_l2v4" name="382" time="0.03"><failure message="sbml_test_suite.cpp(400) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 382))"/></test>
<test suite="SBML_l2v4" name="383" time="0.031"><failure message="sbml_test_suite.cpp(401) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 383))"/></test>
<test suite="SBML_l2v4" name="384" time="0.03"><failure message="sbml_test_suite.cpp(402) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 384))"/></test>
<test suite="SBML_l2v4" name="385" time="0.035"><failure message="sbml_test_suite.cpp(403) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 385))"/></test>
<test suite="SBML_l2v4" name="386" time="0.037"><failure message="sbml_test_suite.cpp(404) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 386))"/></test>
<test suite="SBML_l2v4" name="387" time="0.03"><failure message="sbml_test_suite.cpp(405) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 387))"/></test>
<test suite="SBML_l2v4" name="388" time="0.032"><failure message="sbml_test_suite.cpp(406) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 388))"/></test>
<test suite="SBML_l2v4" name="389" time="0.028"><failure message="sbml_test_suite.cpp(407) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 389))"/></test>
<test suite="SBML_l2v4" name="390" time="0.037"><failure message="sbml_test_suite.cpp(408) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 390))"/></test>
<test suite="SBML_l2v4" name="391" time="0.039"><failure message="sbml_test_suite.cpp(409) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 391))"/></test>
<test suite="SBML_l2v4" name="392" time="0.036"><failure message="sbml_test_suite.cpp(410) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 392))"/></test>
<test suite="SBML_l2v4" name="393" time="0.03"><failure message="sbml_test_suite.cpp(411) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 393))"/></test>
<test suite="SBML_l2v4" name="394" time="0.031"><failure message="sbml_test_suite.cpp(412) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 394))"/></test>
<test suite="SBML_l2v4" name="395" time="0.028"><failure message="sbml_test_suite.cpp(413) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 395))"/></test>
<test suite="SBML_l2v4" name="396" time="0.032"><failure message="sbml_test_suite.cpp(414) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 396))"/></test>
<test suite="SBML_l2v4" name="397" time="0.035"><failure message="sbml_test_suite.cpp(415) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 397))"/></test>
<test suite="SBML_l2v4" name="398" time="0.032"><failure message="sbml_test_suite.cpp(416) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 398))"/></test>
<test suite="SBML_l2v4" name="399" time="0.03"><failure message="sbml_test_suite.cpp(417) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 399))"/></test>
<test suite="SBML_l2v4" name="400" time="0.035"><failure message="sbml_test_suite.cpp(418) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 400))"/></test>
<test suite="SBML_l2v4" name="401" time="0.036"><failure message="sbml_test_suite.cpp(419) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 401))"/></test>
<test suite="SBML_l2v4" name="402" time="0.034"><failure message="sbml_test_suite.cpp(420) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 402))"/></test>
<test suite="SBML_l2v4" name="403" time="0.033"><failure message="sbml_test_suite.cpp(421) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 403))"/></test>
<test suite="SBML_l2v4" name="404" time="0.033"><failure message="sbml_test_suite.cpp(422) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 404))"/></test>
<test suite="SBML_l2v4" name="405" time="0.03"><failure message="sbml_test_suite.cpp(423) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 405))"/></test>
<test suite="SBML_l2v4" name="406" time="0.034"><failure message="sbml_test_suite.cpp(424) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 406))"/></test>
<test suite="SBML_l2v4" name="407" time="0.03"><failure message="sbml_test_suite.cpp(425) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 407))"/></test>
<test suite="SBML_l2v4" name="408" time="0.033"><failure message="sbml_test_suite.cpp(426) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 408))"/></test>
<test suite="SBML_l2v4" name="409" time="0.038"><failure message="sbml_test_suite.cpp(427) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 409))"/></test>
<test suite="SBML_l2v4" name="410" time="0.031"><failure message="sbml_test_suite.cpp(428) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 410))"/></test>
<test suite="SBML_l2v4" name="411" time="0.033"><failure message="sbml_test_suite.cpp(429) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 411))"/></test>
<test suite="SBML_l2v4" name="412" time="0.033"><failure message="sbml_test_suite.cpp(430) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 412))"/></test>
<test suite="SBML_l2v4" name="413" time="0.045"><failure message="sbml_test_suite.cpp(431) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 413))"/></test>
<test suite="SBML_l2v4" name="414" time="0.046"><failure message="sbml_test_suite.cpp(432) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 414))"/></test>
<test suite="SBML_l2v4" name="415" time="0.036"><failure message="sbml_test_suite.cpp(433) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 415))"/></test>
<test suite="SBML_l2v4" name="416" time="0.039"><failure message="sbml_test_suite.cpp(434) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 416))"/></test>
<test suite="SBML_l2v4" name="417" time="0.029"><failure message="sbml_test_suite.cpp(435) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 417))"/></test>
<test suite="SBML_l2v4" name="418" time="0.031"><failure message="sbml_test_suite.cpp(436) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 418))"/></test>
<test suite="SBML_l2v4" name="419" time="0.029"><failure message="sbml_test_suite.cpp(437) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 419))"/></test>
<test suite="SBML_l2v4" name="420" time="0.035"><failure message="sbml_test_suite.cpp(438) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 420))"/></test>
<test suite="SBML_l2v4" name="421" time="0.035"><failure message="sbml_test_suite.cpp(439) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 421))"/></test>
<test suite="SBML_l2v4" name="422" time="0.033"><failure message="sbml_test_suite.cpp(440) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 422))"/></test>
<test suite="SBML_l2v4" name="423" time="0.031"><failure message="sbml_test_suite.cpp(441) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 423))"/></test>
<test suite="SBML_l2v4" name="424" time="0.031"><failure message="sbml_test_suite.cpp(442) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 424))"/></test>
<test suite="SBML_l2v4" name="425" time="0.03"><failure message="sbml_test_suite.cpp(443) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 425))"/></test>
<test suite="SBML_l2v4" name="426" time="0.03"><failure message="sbml_test_suite.cpp(444) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 426))"/></test>
<test suite="SBML_l2v4" name="427" time="0.035"><failure message="sbml_test_suite.cpp(445) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 427))"/></test>
<test suite="SBML_l2v4" name="428" time="0.032"><failure message="sbml_test_suite.cpp(446) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 428))"/></test>
<test suite="SBML_l2v4" name="429" time="0.033"><failure message="sbml_test_suite.cpp(447) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 429))"/></test>
<test suite="SBML_l2v4" name="430" time="0.04"><failure message="sbml_test_suite.cpp(448) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 430))"/></test>
<test suite="SBML_l2v4" name="431" time="0.035"><failure message="sbml_test_suite.cpp(449) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 431))"/></test>
<test suite="SBML_l2v4" name="432" time="0.031"><failure message="sbml_test_suite.cpp(450) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 432))"/></test>
<test suite="SBML_l2v4" name="433" time="0.03"><failure message="sbml_test_suite.cpp(451) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 433))"/></test>
<test suite="SBML_l2v4" name="434" time="0.031"><failure message="sbml_test_suite.cpp(452) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 434))"/></test>
<test suite="SBML_l2v4" name="435" time="0.048"><failure message="sbml_test_suite.cpp(453) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 435))"/></test>
<test suite="SBML_l2v4" name="436" time="0.036"><failure message="sbml_test_suite.cpp(454) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 436))"/></test>
<test suite="SBML_l2v4" name="437" time="0.035"><failure message="sbml_test_suite.cpp(455) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 437))"/></test>
<test suite="SBML_l2v4" name="438" time="0.029"><failure message="sbml_test_suite.cpp(456) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 438))"/></test>
<test suite="SBML_l2v4" name="439" time="0.029"><failure message="sbml_test_suite.cpp(457) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 439))"/></test>
<test suite="SBML_l2v4" name="440" time="0.031"><failure message="sbml_test_suite.cpp(458) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 440))"/></test>
<test suite="SBML_l2v4" name="441" time="0.033"><failure message="sbml_test_suite.cpp(459) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 441))"/></test>
<test suite="SBML_l2v4" name="442" time="0.038"><failure message="sbml_test_suite.cpp(460) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 442))"/></test>
<test suite="SBML_l2v4" name="443" time="0.034"><failure message="sbml_test_suite.cpp(461) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 443))"/></test>
<test suite="SBML_l2v4" name="444" time="0.03"><failure message="sbml_test_suite.cpp(462) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 444))"/></test>
<test suite="SBML_l2v4" name="445" time="0.033"><failure message="sbml_test_suite.cpp(463) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 445))"/></test>
<test suite="SBML_l2v4" name="446" time="0.03"><failure message="sbml_test_suite.cpp(464) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 446))"/></test>
<test suite="SBML_l2v4" name="447" time="0.039"><failure message="sbml_test_suite.cpp(465) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 447))"/></test>
<test suite="SBML_l2v4" name="448" time="0.04"><failure message="sbml_test_suite.cpp(466) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 448))"/></test>
<test suite="SBML_l2v4" name="449" time="0.038"><failure message="sbml_test_suite.cpp(467) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 449))"/></test>
<test suite="SBML_l2v4" name="450" time="0.032"><failure message="sbml_test_suite.cpp(468) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 450))"/></test>
<test suite="SBML_l2v4" name="451" time="0.034"><failure message="sbml_test_suite.cpp(469) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 451))"/></test>
<test suite="SBML_l2v4" name="452" time="0.031"><failure message="sbml_test_suite.cpp(470) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 452))"/></test>
<test suite="SBML_l2v4" name="453" time="0.031"><failure message="sbml_test_suite.cpp(471) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 453))"/></test>
<test suite="SBML_l2v4" name="454" time="0.038"><failure message="sbml_test_suite.cpp(472) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 454))"/></test>
<test suite="SBML_l2v4" name="455" time="0.034"><failure message="sbml_test_suite.cpp(473) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 455))"/></test>
<test suite="SBML_l2v4" name="456" time="0.031"><failure message="sbml_test_suite.cpp(474) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 456))"/></test>
<test suite="SBML_l2v4" name="457" time="0.035"><failure message="sbml_test_suite.cpp(475) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 457))"/></test>
<test suite="SBML_l2v4" name="458" time="0.036"><failure message="sbml_test_suite.cpp(476) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 458))"/></test>
<test suite="SBML_l2v4" name="459" time="0.036"><failure message="sbml_test_suite.cpp(477) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 459))"/></test>
<test suite="SBML_l2v4" name="460" time="0.034"><failure message="sbml_test_suite.cpp(478) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 460))"/></test>
<test suite="SBML_l2v4" name="461" time="0.034"><failure message="sbml_test_suite.cpp(479) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 461))"/></test>
<test suite="SBML_l2v4" name="462" time="0.019"><failure message="sbml_test_suite.cpp(480) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 462))"/></test>
<test suite="SBML_l2v4" name="463" time="0.019"><failure message="sbml_test_suite.cpp(481) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 463))"/></test>
<test suite="SBML_l2v4" name="464" time="0.028"><failure message="sbml_test_suite.cpp(482) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 464))"/></test>
<test suite="SBML_l2v4" name="465" time="0.027"><failure message="sbml_test_suite.cpp(483) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 465))"/></test>
<test suite="SBML_l2v4" name="466" time="0.028"><failure message="sbml_test_suite.cpp(484) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 466))"/></test>
<test suite="SBML_l2v4" name="467" time="0.03"><failure message="sbml_test_suite.cpp(485) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 467))"/></test>
<test suite="SBML_l2v4" name="468" time="0.027"><failure message="sbml_test_suite.cpp(486) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 468))"/></test>
<test suite="SBML_l2v4" name="469" time="0.022"><failure message="sbml_test_suite.cpp(487) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 469))"/></test>
<test suite="SBML_l2v4" name="470" time="0.021"><failure message="sbml_test_suite.cpp(488) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 470))"/></test>
<test suite="SBML_l2v4" name="471" time="0.021"><failure message="sbml_test_suite.cpp(489) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 471))"/></test>
<test suite="SBML_l2v4" name="472" time="0.019"><failure message="sbml_test_suite.cpp(490) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 472))"/></test>
<test suite="SBML_l2v4" name="473" time="0.019"><failure message="sbml_test_suite.cpp(491) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 473))"/></test>
<test suite="SBML_l2v4" name="474" time="0.028"><failure message="sbml_test_suite.cpp(492) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 474))"/></test>
<test suite="SBML_l2v4" name="475" time="0.026"><failure message="sbml_test_suite.cpp(493) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 475))"/></test>
<test suite="SBML_l2v4" name="476" time="0.026"><failure message="sbml_test_suite.cpp(494) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 476))"/></test>
<test suite="SBML_l2v4" name="477" time="0.027"><failure message="sbml_test_suite.cpp(495) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 477))"/></test>
<test suite="SBML_l2v4" name="478" time="0.025"><failure message="sbml_test_suite.cpp(496) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 478))"/></test>
<test suite="SBML_l2v4" name="479" time="0.027"><failure message="sbml_test_suite.cpp(497) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 479))"/></test>
<test suite="SBML_l2v4" name="480" time="0.028"><failure message="sbml_test_suite.cpp(498) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 480))"/></test>
<test suite="SBML_l2v4" name="481" time="0.027"><failure message="sbml_test_suite.cpp(499) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 481))"/></test>
<test suite="SBML_l2v4" name="482" time="0.027"><failure message="sbml_test_suite.cpp(500) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 482))"/></test>
<test suite="SBML_l2v4" name="483" time="0.026"><failure message="sbml_test_suite.cpp(501) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 483))"/></test>
<test suite="SBML_l2v4" name="484" time="0.029"><failure message="sbml_test_suite.cpp(502) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 484))"/></test>
<test suite="SBML_l2v4" name="485" time="0.029"><failure message="sbml_test_suite.cpp(503) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 485))"/></test>
<test suite="SBML_l2v4" name="486" time="0.028"><failure message="sbml_test_suite.cpp(504) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 486))"/></test>
<test suite="SBML_l2v4" name="487" time="0.027"><failure message="sbml_test_suite.cpp(505) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 487))"/></test>
<test suite="SBML_l2v4" name="488" time="0.028"><failure message="sbml_test_suite.cpp(506) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 488))"/></test>
<test suite="SBML_l2v4" name="489" time="0.027"><failure message="sbml_test_suite.cpp(507) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 489))"/></test>
<test suite="SBML_l2v4" name="490" time="0.025"><failure message="sbml_test_suite.cpp(508) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 490))"/></test>
<test suite="SBML_l2v4" name="491" time="0.026"><failure message="sbml_test_suite.cpp(509) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 491))"/></test>
<test suite="SBML_l2v4" name="492" time="0.02"><failure message="sbml_test_suite.cpp(510) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 492))"/></test>
<test suite="SBML_l2v4" name="493" time="0.019"><failure message="sbml_test_suite.cpp(511) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 493))"/></test>
<test suite="SBML_l2v4" name="494" time="0.02"><failure message="sbml_test_suite.cpp(512) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 494))"/></test>
<test suite="SBML_l2v4" name="495" time="0.029"><failure message="sbml_test_suite.cpp(513) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 495))"/></test>
<test suite="SBML_l2v4" name="496" time="0.028"><failure message="sbml_test_suite.cpp(514) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 496))"/></test>
<test suite="SBML_l2v4" name="497" time="0.027"><failure message="sbml_test_suite.cpp(515) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 497))"/></test>
<test suite="SBML_l2v4" name="498" time="0.02"><failure message="sbml_test_suite.cpp(516) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 498))"/></test>
<test suite="SBML_l2v4" name="499" time="0.02"><failure message="sbml_test_suite.cpp(517) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 499))"/></test>
<test suite="SBML_l2v4" name="500" time="0.02"><failure message="sbml_test_suite.cpp(518) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 500))"/></test>
<test suite="SBML_l2v4" name="501" time="0.028"><failure message="sbml_test_suite.cpp(519) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 501))"/></test>
<test suite="SBML_l2v4" name="502" time="0.028"><failure message="sbml_test_suite.cpp(520) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 502))"/></test>
<test suite="SBML_l2v4" name="503" time="0.031"><failure message="sbml_test_suite.cpp(521) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 503))"/></test>
<test suite="SBML_l2v4" name="504" time="0.028"><failure message="sbml_test_suite.cpp(522) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 504))"/></test>
<test suite="SBML_l2v4" name="505" time="0.03"><failure message="sbml_test_suite.cpp(523) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 505))"/></test>
<test suite="SBML_l2v4" name="506" time="0.03"><failure message="sbml_test_suite.cpp(524) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 506))"/></test>
<test suite="SBML_l2v4" name="507" time="0.023"><failure message="sbml_test_suite.cpp(525) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 507))"/></test>
<test suite="SBML_l2v4" name="508" time="0.023"><failure message="sbml_test_suite.cpp(526) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 508))"/></test>
<test suite="SBML_l2v4" name="509" time="0.022"><failure message="sbml_test_suite.cpp(527) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 509))"/></test>
<test suite="SBML_l2v4" name="510" time="0.021"><failure message="sbml_test_suite.cpp(528) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 510))"/></test>
<test suite="SBML_l2v4" name="511" time="0.02"><failure message="sbml_test_suite.cpp(529) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 511))"/></test>
<test suite="SBML_l2v4" name="512" time="0.02"><failure message="sbml_test_suite.cpp(530) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 512))"/></test>
<test suite="SBML_l2v4" name="513" time="0.028"><failure message="sbml_test_suite.cpp(531) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 513))"/></test>
<test suite="SBML_l2v4" name="514" time="0.029"><failure message="sbml_test_suite.cpp(532) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 514))"/></test>
<test suite="SBML_l2v4" name="515" time="0.028"><failure message="sbml_test_suite.cpp(533) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 515))"/></test>
<test suite="SBML_l2v4" name="516" time="0.032"><failure message="sbml_test_suite.cpp(534) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 516))"/></test>
<test suite="SBML_l2v4" name="517" time="0.024"><failure message="sbml_test_suite.cpp(535) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 517))"/></test>
<test suite="SBML_l2v4" name="518" time="0.025"><failure message="sbml_test_suite.cpp(536) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 518))"/></test>
<test suite="SBML_l2v4" name="519" time="0.031"><failure message="sbml_test_suite.cpp(537) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 519))"/></test>
<test suite="SBML_l2v4" name="520" time="0.031"><failure message="sbml_test_suite.cpp(538) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 520))"/></test>
<test suite="SBML_l2v4" name="521" time="0.03"><failure message="sbml_test_suite.cpp(539) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 521))"/></test>
<test suite="SBML_l2v4" name="522" time="0.03"><failure message="sbml_test_suite.cpp(540) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 522))"/></test>
<test suite="SBML_l2v4" name="523" time="0.028"><failure message="sbml_test_suite.cpp(541) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 523))"/></test>
<test suite="SBML_l2v4" name="524" time="0.028"><failure message="sbml_test_suite.cpp(542) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 524))"/></test>
<test suite="SBML_l2v4" name="525" time="0.023"><failure message="sbml_test_suite.cpp(543) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 525))"/></test>
<test suite="SBML_l2v4" name="526" time="0.021"><failure message="sbml_test_suite.cpp(544) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 526))"/></test>
<test suite="SBML_l2v4" name="527" time="0.021"><failure message="sbml_test_suite.cpp(545) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 527))"/></test>
<test suite="SBML_l2v4" name="528" time="0.027"><failure message="sbml_test_suite.cpp(546) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 528))"/></test>
<test suite="SBML_l2v4" name="529" time="0.024"><failure message="sbml_test_suite.cpp(547) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 529))"/></test>
<test suite="SBML_l2v4" name="530" time="0.024"><failure message="sbml_test_suite.cpp(548) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 530))"/></test>
<test suite="SBML_l2v4" name="532" time="0.029"><failure message="sbml_test_suite.cpp(550) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 532))"/></test>
<test suite="SBML_l2v4" name="539" time="0.027"><failure message="sbml_test_suite.cpp(557) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 539))"/></test>
<test suite="SBML_l2v4" name="540" time="0.028"><failure message="sbml_test_suite.cpp(558) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 540))"/></test>
<test suite="SBML_l2v4" name="541" time="0.033"><failure message="sbml_test_suite.cpp(559) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 541))"/></test>
<test suite="SBML_l2v4" name="542" time="0.025"><failure message="sbml_test_suite.cpp(560) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 542))"/></test>
<test suite="SBML_l2v4" name="544" time="0.027"><failure message="sbml_test_suite.cpp(562) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 544))"/></test>
<test suite="SBML_l2v4" name="545" time="0.13"><failure message="sbml_test_suite.cpp(563) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 545))"/></test>
<test suite="SBML_l2v4" name="547" time="0.026"><failure message="sbml_test_suite.cpp(565) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 547))"/></test>
<test suite="SBML_l2v4" name="568" time="0.031"><failure message="sbml_test_suite.cpp(586) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 568))"/></test>
<test suite="SBML_l2v4" name="572" time="0.031"><failure message="sbml_test_suite.cpp(590) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 572))"/></test>
<test suite="SBML_l2v4" name="574" time="0.025"><failure message="sbml_test_suite.cpp(592) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 574))"/></test>
<test suite="SBML_l2v4" name="577" time="0.027"><failure message="sbml_test_suite.cpp(595) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 577))"/></test>
<test suite="SBML_l2v4" name="578" time="0.023"><failure message="sbml_test_suite.cpp(596) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 578))"/></test>
<test suite="SBML_l2v4" name="579" time="0.025"><failure message="sbml_test_suite.cpp(597) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 579))"/></test>
<test suite="SBML_l2v4" name="580" time="0.026"><failure message="sbml_test_suite.cpp(598) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 580))"/></test>
<test suite="SBML_l2v4" name="581" time="0.025"><failure message="sbml_test_suite.cpp(599) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 581))"/></test>
<test suite="SBML_l2v4" name="582" time="0.026"><failure message="sbml_test_suite.cpp(600) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 582))"/></test>
<test suite="SBML_l2v4" name="583" time="0.026"><failure message="sbml_test_suite.cpp(601) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 583))"/></test>
<test suite="SBML_l2v4" name="584" time="0.032"><failure message="sbml_test_suite.cpp(602) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 584))"/></test>
<test suite="SBML_l2v4" name="585" time="0.029"><failure message="sbml_test_suite.cpp(603) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 585))"/></test>
<test suite="SBML_l2v4" name="586" time="0.018"><failure message="sbml_test_suite.cpp(604) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 586))"/></test>
<test suite="SBML_l2v4" name="587" time="0.026"><failure message="sbml_test_suite.cpp(605) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 587))"/></test>
<test suite="SBML_l2v4" name="588" time="0.024"><failure message="sbml_test_suite.cpp(606) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 588))"/></test>
<test suite="SBML_l2v4" name="589" time="0.018"><failure message="sbml_test_suite.cpp(607) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 589))"/></test>
<test suite="SBML_l2v4" name="590" time="0.025"><failure message="sbml_test_suite.cpp(608) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 590))"/></test>
<test suite="SBML_l2v4" name="591" time="0.027"><failure message="sbml_test_suite.cpp(609) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 591))"/></test>
<test suite="SBML_l2v4" name="592" time="0.017"><failure message="sbml_test_suite.cpp(610) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 592))"/></test>
<test suite="SBML_l2v4" name="593" time="0.023"><failure message="sbml_test_suite.cpp(611) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 593))"/></test>
<test suite="SBML_l2v4" name="594" time="0.025"><failure message="sbml_test_suite.cpp(612) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 594))"/></test>
<test suite="SBML_l2v4" name="595" time="0.024"><failure message="sbml_test_suite.cpp(613) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 595))"/></test>
<test suite="SBML_l2v4" name="596" time="0.027"><failure message="sbml_test_suite.cpp(614) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 596))"/></test>
<test suite="SBML_l2v4" name="597" time="0.025"><failure message="sbml_test_suite.cpp(615) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 597))"/></test>
<test suite="SBML_l2v4" name="598" time="0.019"><failure message="sbml_test_suite.cpp(616) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 598))"/></test>
<test suite="SBML_l2v4" name="599" time="0.028"><failure message="sbml_test_suite.cpp(617) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 599))"/></test>
<test suite="SBML_l2v4" name="600" time="0.03"><failure message="sbml_test_suite.cpp(618) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 600))"/></test>
<test suite="SBML_l2v4" name="601" time="0.019"><failure message="sbml_test_suite.cpp(619) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 601))"/></test>
<test suite="SBML_l2v4" name="602" time="0.025"><failure message="sbml_test_suite.cpp(620) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 602))"/></test>
<test suite="SBML_l2v4" name="603" time="0.032"><failure message="sbml_test_suite.cpp(621) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 603))"/></test>
<test suite="SBML_l2v4" name="604" time="0.021"><failure message="sbml_test_suite.cpp(622) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 604))"/></test>
<test suite="SBML_l2v4" name="605" time="0.029"><failure message="sbml_test_suite.cpp(623) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 605))"/></test>
<test suite="SBML_l2v4" name="606" time="0.029"><failure message="sbml_test_suite.cpp(624) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 606))"/></test>
<test suite="SBML_l2v4" name="607" time="0.028"><failure message="sbml_test_suite.cpp(625) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 607))"/></test>
<test suite="SBML_l2v4" name="608" time="0.022"><failure message="sbml_test_suite.cpp(626) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 608))"/></test>
<test suite="SBML_l2v4" name="609" time="0.024"><failure message="sbml_test_suite.cpp(627) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 609))"/></test>
<test suite="SBML_l2v4" name="610" time="0.031"><failure message="sbml_test_suite.cpp(628) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 610))"/></test>
<test suite="SBML_l2v4" name="611" time="0.023"><failure message="sbml_test_suite.cpp(629) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 611))"/></test>
<test suite="SBML_l2v4" name="612" time="0.028"><failure message="sbml_test_suite.cpp(630) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 612))"/></test>
<test suite="SBML_l2v4" name="616" time="0.022"><failure message="sbml_test_suite.cpp(634) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 616))"/></test>
<test suite="SBML_l2v4" name="617" time="0.023"><failure message="sbml_test_suite.cpp(635) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 617))"/></test>
<test suite="SBML_l2v4" name="618" time="0.02"><failure message="sbml_test_suite.cpp(636) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 618))"/></test>
<test suite="SBML_l2v4" name="619" time="0.025"><failure message="sbml_test_suite.cpp(637) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 619))"/></test>
<test suite="SBML_l2v4" name="620" time="0.024"><failure message="sbml_test_suite.cpp(638) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 620))"/></test>
<test suite="SBML_l2v4" name="621" time="0.024"><failure message="sbml_test_suite.cpp(639) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 621))"/></test>
<test suite="SBML_l2v4" name="622" time="0.028"><failure message="sbml_test_suite.cpp(640) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 622))"/></test>
<test suite="SBML_l2v4" name="623" time="0.028"><failure message="sbml_test_suite.cpp(641) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 623))"/></test>
<test suite="SBML_l2v4" name="624" time="0.027"><failure message="sbml_test_suite.cpp(642) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 624))"/></test>
<test suite="SBML_l2v4" name="625" time="0.035"><failure message="sbml_test_suite.cpp(643) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 625))"/></test>
<test suite="SBML_l2v4" name="626" time="0.036"><failure message="sbml_test_suite.cpp(644) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 626))"/></test>
<test suite="SBML_l2v4" name="627" time="0.034"><failure message="sbml_test_suite.cpp(645) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 627))"/></test>
<test suite="SBML_l2v4" name="631" time="0.025"><failure message="sbml_test_suite.cpp(649) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 631))"/></test>
<test suite="SBML_l2v4" name="632" time="0.027"><failure message="sbml_test_suite.cpp(650) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 632))"/></test>
<test suite="SBML_l2v4" name="633" time="0.027"><failure message="sbml_test_suite.cpp(651) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 633))"/></test>
<test suite="SBML_l2v4" name="634" time="0.029"><failure message="sbml_test_suite.cpp(652) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 634))"/></test>
<test suite="SBML_l2v4" name="635" time="0.029"><failure message="sbml_test_suite.cpp(653) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 635))"/></test>
<test suite="SBML_l2v4" name="636" time="0.029"><failure message="sbml_test_suite.cpp(654) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 636))"/></test>
<test suite="SBML_l2v4" name="637" time="0.03"><failure message="sbml_test_suite.cpp(655) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 637))"/></test>
<test suite="SBML_l2v4" name="638" time="0.031"><failure message="sbml_test_suite.cpp(656) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 638))"/></test>
<test suite="SBML_l2v4" name="639" time="0.052"><failure message="sbml_test_suite.cpp(657) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 639))"/></test>
<test suite="SBML_l2v4" name="640" time="0.029"><failure message="sbml_test_suite.cpp(658) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 640))"/></test>
<test suite="SBML_l2v4" name="641" time="0.028"><failure message="sbml_test_suite.cpp(659) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 641))"/></test>
<test suite="SBML_l2v4" name="642" time="0.028"><failure message="sbml_test_suite.cpp(660) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 642))"/></test>
<test suite="SBML_l2v4" name="643" time="0.041"><failure message="sbml_test_suite.cpp(661) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 643))"/></test>
<test suite="SBML_l2v4" name="644" time="0.036"><failure message="sbml_test_suite.cpp(662) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 644))"/></test>
<test suite="SBML_l2v4" name="645" time="0.033"><failure message="sbml_test_suite.cpp(663) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 645))"/></test>
<test suite="SBML_l2v4" name="646" time="0.025"><failure message="sbml_test_suite.cpp(664) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 646))"/></test>
<test suite="SBML_l2v4" name="647" time="0.031"><failure message="sbml_test_suite.cpp(665) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 647))"/></test>
<test suite="SBML_l2v4" name="648" time="0.028"><failure message="sbml_test_suite.cpp(666) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 648))"/></test>
<test suite="SBML_l2v4" name="649" time="0.026"><failure message="sbml_test_suite.cpp(667) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 649))"/></test>
<test suite="SBML_l2v4" name="650" time="0.033"><failure message="sbml_test_suite.cpp(668) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 650))"/></test>
<test suite="SBML_l2v4" name="651" time="0.031"><failure message="sbml_test_suite.cpp(669) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 651))"/></test>
<test suite="SBML_l2v4" name="652" time="0.037"><failure message="sbml_test_suite.cpp(670) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 652))"/></test>
<test suite="SBML_l2v4" name="653" time="0.036"><failure message="sbml_test_suite.cpp(671) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 653))"/></test>
<test suite="SBML_l2v4" name="654" time="0.037"><failure message="sbml_test_suite.cpp(672) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 654))"/></test>
<test suite="SBML_l2v4" name="655" time="0.038"><failure message="sbml_test_suite.cpp(673) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 655))"/></test>
<test suite="SBML_l2v4" name="656" time="0.036"><failure message="sbml_test_suite.cpp(674) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 656))"/></test>
<test suite="SBML_l2v4" name="657" time="0.037"><failure message="sbml_test_suite.cpp(675) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 657))"/></test>
<test suite="SBML_l2v4" name="667" time="0.027"><failure message="sbml_test_suite.cpp(685) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 667))"/></test>
<test suite="SBML_l2v4" name="668" time="0.032"><failure message="sbml_test_suite.cpp(686) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 668))"/></test>
<test suite="SBML_l2v4" name="669" time="0.038"><failure message="sbml_test_suite.cpp(687) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 669))"/></test>
<test suite="SBML_l2v4" name="670" time="0.032"><failure message="sbml_test_suite.cpp(688) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 670))"/></test>
<test suite="SBML_l2v4" name="671" time="0.032"><failure message="sbml_test_suite.cpp(689) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 671))"/></test>
<test suite="SBML_l2v4" name="672" time="0.031"><failure message="sbml_test_suite.cpp(690) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 672))"/></test>
<test suite="SBML_l2v4" name="676" time="0.019"><failure message="sbml_test_suite.cpp(694) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 676))"/></test>
<test suite="SBML_l2v4" name="677" time="0.02"><failure message="sbml_test_suite.cpp(695) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 677))"/></test>
<test suite="SBML_l2v4" name="678" time="0.021"><failure message="sbml_test_suite.cpp(696) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 678))"/></test>
<test suite="SBML_l2v4" name="679" time="0.026"><failure message="sbml_test_suite.cpp(697) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 679))"/></test>
<test suite="SBML_l2v4" name="680" time="0.025"><failure message="sbml_test_suite.cpp(698) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 680))"/></test>
<test suite="SBML_l2v4" name="681" time="0.031"><failure message="sbml_test_suite.cpp(699) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 681))"/></test>
<test suite="SBML_l2v4" name="682" time="0.027"><failure message="sbml_test_suite.cpp(700) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 682))"/></test>
<test suite="SBML_l2v4" name="683" time="0.025"><failure message="sbml_test_suite.cpp(701) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 683))"/></test>
<test suite="SBML_l2v4" name="684" time="0.028"><failure message="sbml_test_suite.cpp(702) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 684))"/></test>
<test suite="SBML_l2v4" name="685" time="0.025"><failure message="sbml_test_suite.cpp(703) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 685))"/></test>
<test suite="SBML_l2v4" name="686" time="0.03"><failure message="sbml_test_suite.cpp(704) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 686))"/></test>
<test suite="SBML_l2v4" name="688" time="0.02"><failure message="sbml_test_suite.cpp(706) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 688))"/></test>
<test suite="SBML_l2v4" name="689" time="0.027"><failure message="sbml_test_suite.cpp(707) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 689))"/></test>
<test suite="SBML_l2v4" name="690" time="0.028"><failure message="sbml_test_suite.cpp(708) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 690))"/></test>
<test suite="SBML_l2v4" name="691" time="0.023"><failure message="sbml_test_suite.cpp(709) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 691))"/></test>
<test suite="SBML_l2v4" name="692" time="0.024"><failure message="sbml_test_suite.cpp(710) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 692))"/></test>
<test suite="SBML_l2v4" name="693" time="0.03"><failure message="sbml_test_suite.cpp(711) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 693))"/></test>
<test suite="SBML_l2v4" name="694" time="0.031"><failure message="sbml_test_suite.cpp(712) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 694))"/></test>
<test suite="SBML_l2v4" name="697" time="0.021"><failure message="sbml_test_suite.cpp(715) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 697))"/></test>
<test suite="SBML_l2v4" name="698" time="0.022"><failure message="sbml_test_suite.cpp(716) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 698))"/></test>
<test suite="SBML_l2v4" name="699" time="0.026"><failure message="sbml_test_suite.cpp(717) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 699))"/></test>
<test suite="SBML_l2v4" name="700" time="0.024"><failure message="sbml_test_suite.cpp(718) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 700))"/></test>
<test suite="SBML_l2v4" name="701" time="0.026"><failure message="sbml_test_suite.cpp(719) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 701))"/></test>
<test suite="SBML_l2v4" name="702" time="0.028"><failure message="sbml_test_suite.cpp(720) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 702))"/></test>
<test suite="SBML_l2v4" name="703" time="0.032"><failure message="sbml_test_suite.cpp(721) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 703))"/></test>
<test suite="SBML_l2v4" name="704" time="0.033"><failure message="sbml_test_suite.cpp(722) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 704))"/></test>
<test suite="SBML_l2v4" name="706" time="0.023"><failure message="sbml_test_suite.cpp(724) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 706))"/></test>
<test suite="SBML_l2v4" name="707" time="0.026"><failure message="sbml_test_suite.cpp(725) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 707))"/></test>
<test suite="SBML_l2v4" name="708" time="0.027"><failure message="sbml_test_suite.cpp(726) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 708))"/></test>
<test suite="SBML_l2v4" name="709" time="0.023"><failure message="sbml_test_suite.cpp(727) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 709))"/></test>
<test suite="SBML_l2v4" name="710" time="0.021"><failure message="sbml_test_suite.cpp(728) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 710))"/></test>
<test suite="SBML_l2v4" name="711" time="0.026"><failure message="sbml_test_suite.cpp(729) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 711))"/></test>
<test suite="SBML_l2v4" name="712" time="0.024"><failure message="sbml_test_suite.cpp(730) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 712))"/></test>
<test suite="SBML_l2v4" name="713" time="0.035"><failure message="sbml_test_suite.cpp(731) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 713))"/></test>
<test suite="SBML_l2v4" name="714" time="0.036"><failure message="sbml_test_suite.cpp(732) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 714))"/></test>
<test suite="SBML_l2v4" name="715" time="0.032"><failure message="sbml_test_suite.cpp(733) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 715))"/></test>
<test suite="SBML_l2v4" name="716" time="0.032"><failure message="sbml_test_suite.cpp(734) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 716))"/></test>
<test suite="SBML_l2v4" name="717" time="0.022"><failure message="sbml_test_suite.cpp(735) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 717))"/></test>
<test suite="SBML_l2v4" name="718" time="0.028"><failure message="sbml_test_suite.cpp(736) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 718))"/></test>
<test suite="SBML_l2v4" name="719" time="0.025"><failure message="sbml_test_suite.cpp(737) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 719))"/></test>
<test suite="SBML_l2v4" name="720" time="0.031"><failure message="sbml_test_suite.cpp(738) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 720))"/></test>
<test suite="SBML_l2v4" name="721" time="0.031"><failure message="sbml_test_suite.cpp(739) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 721))"/></test>
<test suite="SBML_l2v4" name="722" time="0.029"><failure message="sbml_test_suite.cpp(740) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 722))"/></test>
<test suite="SBML_l2v4" name="723" time="0.028"><failure message="sbml_test_suite.cpp(741) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 723))"/></test>
<test suite="SBML_l2v4" name="724" time="0.031"><failure message="sbml_test_suite.cpp(742) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 724))"/></test>
<test suite="SBML_l2v4" name="725" time="0.029"><failure message="sbml_test_suite.cpp(743) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 725))"/></test>
<test suite="SBML_l2v4" name="726" time="0.027"><failure message="sbml_test_suite.cpp(744) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 726))"/></test>
<test suite="SBML_l2v4" name="727" time="0.033"><failure message="sbml_test_suite.cpp(745) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 727))"/></test>
<test suite="SBML_l2v4" name="728" time="0.033"><failure message="sbml_test_suite.cpp(746) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 728))"/></test>
<test suite="SBML_l2v4" name="729" time="0.029"><failure message="sbml_test_suite.cpp(747) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 729))"/></test>
<test suite="SBML_l2v4" name="730" time="0.03"><failure message="sbml_test_suite.cpp(748) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 730))"/></test>
<test suite="SBML_l2v4" name="731" time="0.033"><failure message="sbml_test_suite.cpp(749) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 731))"/></test>
<test suite="SBML_l2v4" name="732" time="0.024"><failure message="sbml_test_suite.cpp(750) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 732))"/></test>
<test suite="SBML_l2v4" name="733" time="0.032"><failure message="sbml_test_suite.cpp(751) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 733))"/></test>
<test suite="SBML_l2v4" name="734" time="0.032"><failure message="sbml_test_suite.cpp(752) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 734))"/></test>
<test suite="SBML_l2v4" name="735" time="0.028"><failure message="sbml_test_suite.cpp(753) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 735))"/></test>
<test suite="SBML_l2v4" name="736" time="0.031"><failure message="sbml_test_suite.cpp(754) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 736))"/></test>
<test suite="SBML_l2v4" name="737" time="0.03"><failure message="sbml_test_suite.cpp(755) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 737))"/></test>
<test suite="SBML_l2v4" name="738" time="0.031"><failure message="sbml_test_suite.cpp(756) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 738))"/></test>
<test suite="SBML_l2v4" name="739" time="0.039"><failure message="sbml_test_suite.cpp(757) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 739))"/></test>
<test suite="SBML_l2v4" name="740" time="0.025"><failure message="sbml_test_suite.cpp(758) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 740))"/></test>
<test suite="SBML_l2v4" name="741" time="0.033"><failure message="sbml_test_suite.cpp(759) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 741))"/></test>
<test suite="SBML_l2v4" name="742" time="0.033"><failure message="sbml_test_suite.cpp(760) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 742))"/></test>
<test suite="SBML_l2v4" name="743" time="0.028"><failure message="sbml_test_suite.cpp(761) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 743))"/></test>
<test suite="SBML_l2v4" name="744" time="0.034"><failure message="sbml_test_suite.cpp(762) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 744))"/></test>
<test suite="SBML_l2v4" name="745" time="0.03"><failure message="sbml_test_suite.cpp(763) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 745))"/></test>
<test suite="SBML_l2v4" name="746" time="0.031"><failure message="sbml_test_suite.cpp(764) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 746))"/></test>
<test suite="SBML_l2v4" name="747" time="0.036"><failure message="sbml_test_suite.cpp(765) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 747))"/></test>
<test suite="SBML_l2v4" name="748" time="0.032"><failure message="sbml_test_suite.cpp(766) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 748))"/></test>
<test suite="SBML_l2v4" name="749" time="0.027"><failure message="sbml_test_suite.cpp(767) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 749))"/></test>
<test suite="SBML_l2v4" name="750" time="0.027"><failure message="sbml_test_suite.cpp(768) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 750))"/></test>
<test suite="SBML_l2v4" name="751" time="0.04"><failure message="sbml_test_suite.cpp(769) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 751))"/></test>
<test suite="SBML_l2v4" name="752" time="0.047"><failure message="sbml_test_suite.cpp(770) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 752))"/></test>
<test suite="SBML_l2v4" name="753" time="0.042"><failure message="sbml_test_suite.cpp(771) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 753))"/></test>
<test suite="SBML_l2v4" name="754" time="0.035"><failure message="sbml_test_suite.cpp(772) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 754))"/></test>
<test suite="SBML_l2v4" name="755" time="0.037"><failure message="sbml_test_suite.cpp(773) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 755))"/></test>
<test suite="SBML_l2v4" name="756" time="0.038"><failure message="sbml_test_suite.cpp(774) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 756))"/></test>
<test suite="SBML_l2v4" name="757" time="0.043"><failure message="sbml_test_suite.cpp(775) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 757))"/></test>
<test suite="SBML_l2v4" name="758" time="0.044"><failure message="sbml_test_suite.cpp(776) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 758))"/></test>
<test suite="SBML_l2v4" name="759" time="0.044"><failure message="sbml_test_suite.cpp(777) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 759))"/></test>
<test suite="SBML_l2v4" name="763" time="0.028"><failure message="sbml_test_suite.cpp(781) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 763))"/></test>
<test suite="SBML_l2v4" name="764" time="0.033"><failure message="sbml_test_suite.cpp(782) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 764))"/></test>
<test suite="SBML_l2v4" name="765" time="0.03"><failure message="sbml_test_suite.cpp(783) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 765))"/></test>
<test suite="SBML_l2v4" name="766" time="0.032"><failure message="sbml_test_suite.cpp(784) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 766))"/></test>
<test suite="SBML_l2v4" name="767" time="0.038"><failure message="sbml_test_suite.cpp(785) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 767))"/></test>
<test suite="SBML_l2v4" name="768" time="0.034"><failure message="sbml_test_suite.cpp(786) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 768))"/></test>
<test suite="SBML_l2v4" name="769" time="0.029"><failure message="sbml_test_suite.cpp(787) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 769))"/></test>
<test suite="SBML_l2v4" name="770" time="0.026"><failure message="sbml_test_suite.cpp(788) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 770))"/></test>
<test suite="SBML_l2v4" name="771" time="0.032"><failure message="sbml_test_suite.cpp(789) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 771))"/></test>
<test suite="SBML_l2v4" name="772" time="0.032"><failure message="sbml_test_suite.cpp(790) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 772))"/></test>
<test suite="SBML_l2v4" name="773" time="0.034"><failure message="sbml_test_suite.cpp(791) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 773))"/></test>
<test suite="SBML_l2v4" name="774" time="0.032"><failure message="sbml_test_suite.cpp(792) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 774))"/></test>
<test suite="SBML_l2v4" name="775" time="0.037"><failure message="sbml_test_suite.cpp(793) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 775))"/></test>
<test suite="SBML_l2v4" name="776" time="0.037"><failure message="sbml_test_suite.cpp(794) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 776))"/></test>
<test suite="SBML_l2v4" name="781" time="0.025"><failure message="sbml_test_suite.cpp(799) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 781))"/></test>
<test suite="SBML_l2v4" name="782" time="0.02"><failure message="sbml_test_suite.cpp(800) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 782))"/></test>
<test suite="SBML_l2v4" name="783" time="0.021"><failure message="sbml_test_suite.cpp(801) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 783))"/></test>
<test suite="SBML_l2v4" name="784" time="0.026"><failure message="sbml_test_suite.cpp(802) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 784))"/></test>
<test suite="SBML_l2v4" name="785" time="0.026"><failure message="sbml_test_suite.cpp(803) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 785))"/></test>
<test suite="SBML_l2v4" name="786" time="0.026"><failure message="sbml_test_suite.cpp(804) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 786))"/></test>
<test suite="SBML_l2v4" name="787" time="0.022"><failure message="sbml_test_suite.cpp(805) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 787))"/></test>
<test suite="SBML_l2v4" name="788" time="0.025"><failure message="sbml_test_suite.cpp(806) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 788))"/></test>
<test suite="SBML_l2v4" name="789" time="0.031"><failure message="sbml_test_suite.cpp(807) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 789))"/></test>
<test suite="SBML_l2v4" name="790" time="0.033"><failure message="sbml_test_suite.cpp(808) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 790))"/></test>
<test suite="SBML_l2v4" name="791" time="0.032"><failure message="sbml_test_suite.cpp(809) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 791))"/></test>
<test suite="SBML_l2v4" name="792" time="0.021"><failure message="sbml_test_suite.cpp(810) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 792))"/></test>
<test suite="SBML_l2v4" name="793" time="0.021"><failure message="sbml_test_suite.cpp(811) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 793))"/></test>
<test suite="SBML_l2v4" name="794" time="0.022"><failure message="sbml_test_suite.cpp(812) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 794))"/></test>
<test suite="SBML_l2v4" name="795" time="0.023"><failure message="sbml_test_suite.cpp(813) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 795))"/></test>
<test suite="SBML_l2v4" name="796" time="0.021"><failure message="sbml_test_suite.cpp(814) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 796))"/></test>
<test suite="SBML_l2v4" name="797" time="0.029"><failure message="sbml_test_suite.cpp(815) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 797))"/></test>
<test suite="SBML_l2v4" name="798" time="0.026"><failure message="sbml_test_suite.cpp(816) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 798))"/></test>
<test suite="SBML_l2v4" name="799" time="0.027"><failure message="sbml_test_suite.cpp(817) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 799))"/></test>
<test suite="SBML_l2v4" name="800" time="0.029"><failure message="sbml_test_suite.cpp(818) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 800))"/></test>
<test suite="SBML_l2v4" name="801" time="0.017"><failure message="sbml_test_suite.cpp(819) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 801))"/></test>
<test suite="SBML_l2v4" name="802" time="0.018"><failure message="sbml_test_suite.cpp(820) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 802))"/></test>
<test suite="SBML_l2v4" name="803" time="0.019"><failure message="sbml_test_suite.cpp(821) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 803))"/></test>
<test suite="SBML_l2v4" name="804" time="0.019"><failure message="sbml_test_suite.cpp(822) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 804))"/></test>
<test suite="SBML_l2v4" name="805" time="0.018"><failure message="sbml_test_suite.cpp(823) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 805))"/></test>
<test suite="SBML_l2v4" name="806" time="0.019"><failure message="sbml_test_suite.cpp(824) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 806))"/></test>
<test suite="SBML_l2v4" name="807" time="0.02"><failure message="sbml_test_suite.cpp(825) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 807))"/></test>
<test suite="SBML_l2v4" name="808" time="0.021"><failure message="sbml_test_suite.cpp(826) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 808))"/></test>
<test suite="SBML_l2v4" name="809" time="0.023"><failure message="sbml_test_suite.cpp(827) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 809))"/></test>
<test suite="SBML_l2v4" name="810" time="0.02"><failure message="sbml_test_suite.cpp(828) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 810))"/></test>
<test suite="SBML_l2v4" name="811" time="0.023"><failure message="sbml_test_suite.cpp(829) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 811))"/></test>
<test suite="SBML_l2v4" name="812" time="0.02"><failure message="sbml_test_suite.cpp(830) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 812))"/></test>
<test suite="SBML_l2v4" name="813" time="0.022"><failure message="sbml_test_suite.cpp(831) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 813))"/></test>
<test suite="SBML_l2v4" name="814" time="0.021"><failure message="sbml_test_suite.cpp(832) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 814))"/></test>
<test suite="SBML_l2v4" name="815" time="0.02"><failure message="sbml_test_suite.cpp(833) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 815))"/></test>
<test suite="SBML_l2v4" name="816" time="0.021"><failure message="sbml_test_suite.cpp(834) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 816))"/></test>
<test suite="SBML_l2v4" name="817" time="0.021"><failure message="sbml_test_suite.cpp(835) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 817))"/></test>
<test suite="SBML_l2v4" name="818" time="0.02"><failure message="sbml_test_suite.cpp(836) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 818))"/></test>
<test suite="SBML_l2v4" name="819" time="0.021"><failure message="sbml_test_suite.cpp(837) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 819))"/></test>
<test suite="SBML_l2v4" name="820" time="0.022"><failure message="sbml_test_suite.cpp(838) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 820))"/></test>
<test suite="SBML_l2v4" name="821" time="0.02"><failure message="sbml_test_suite.cpp(839) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 821))"/></test>
<test suite="SBML_l2v4" name="822" time="0.02"><failure message="sbml_test_suite.cpp(840) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 822))"/></test>
<test suite="SBML_l2v4" name="823" time="0.021"><failure message="sbml_test_suite.cpp(841) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 823))"/></test>
<test suite="SBML_l2v4" name="824" time="0.022"><failure message="sbml_test_suite.cpp(842) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 824))"/></test>
<test suite="SBML_l2v4" name="825" time="0.022"><failure message="sbml_test_suite.cpp(843) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 825))"/></test>
<test suite="SBML_l2v4" name="826" time="0.021"><failure message="sbml_test_suite.cpp(844) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 826))"/></test>
<test suite="SBML_l2v4" name="827" time="0.021"><failure message="sbml_test_suite.cpp(845) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 827))"/></test>
<test suite="SBML_l2v4" name="828" time="0.025"><failure message="sbml_test_suite.cpp(846) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 828))"/></test>
<test suite="SBML_l2v4" name="829" time="0.024"><failure message="sbml_test_suite.cpp(847) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 829))"/></test>
<test suite="SBML_l2v4" name="830" time="0.031"><failure message="sbml_test_suite.cpp(848) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 830))"/></test>
<test suite="SBML_l2v4" name="831" time="0.031"><failure message="sbml_test_suite.cpp(849) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 831))"/></test>
<test suite="SBML_l2v4" name="832" time="0.023"><failure message="sbml_test_suite.cpp(850) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 832))"/></test>
<test suite="SBML_l2v4" name="833" time="0.025"><failure message="sbml_test_suite.cpp(851) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 833))"/></test>
<test suite="SBML_l2v4" name="834" time="0.029"><failure message="sbml_test_suite.cpp(852) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 834))"/></test>
<test suite="SBML_l2v4" name="835" time="0.024"><failure message="sbml_test_suite.cpp(853) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 835))"/></test>
<test suite="SBML_l2v4" name="836" time="0.025"><failure message="sbml_test_suite.cpp(854) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 836))"/></test>
<test suite="SBML_l2v4" name="837" time="0.024"><failure message="sbml_test_suite.cpp(855) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 837))"/></test>
<test suite="SBML_l2v4" name="838" time="0.023"><failure message="sbml_test_suite.cpp(856) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 838))"/></test>
<test suite="SBML_l2v4" name="839" time="0.028"><failure message="sbml_test_suite.cpp(857) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 839))"/></test>
<test suite="SBML_l2v4" name="840" time="0.027"><failure message="sbml_test_suite.cpp(858) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 840))"/></test>
<test suite="SBML_l2v4" name="841" time="0.03"><failure message="sbml_test_suite.cpp(859) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 841))"/></test>
<test suite="SBML_l2v4" name="842" time="0.025"><failure message="sbml_test_suite.cpp(860) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 842))"/></test>
<test suite="SBML_l2v4" name="843" time="0.024"><failure message="sbml_test_suite.cpp(861) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 843))"/></test>
<test suite="SBML_l2v4" name="845" time="0.027"><failure message="sbml_test_suite.cpp(863) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 845))"/></test>
<test suite="SBML_l2v4" name="846" time="0.035"><failure message="sbml_test_suite.cpp(864) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 846))"/></test>
<test suite="SBML_l2v4" name="847" time="0.039"><failure message="sbml_test_suite.cpp(865) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 847))"/></test>
<test suite="SBML_l2v4" name="848" time="0.024"><failure message="sbml_test_suite.cpp(866) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 848))"/></test>
<test suite="SBML_l2v4" name="849" time="0.035"><failure message="sbml_test_suite.cpp(867) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 849))"/></test>
<test suite="SBML_l2v4" name="850" time="0.041"><failure message="sbml_test_suite.cpp(868) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 850))"/></test>
<test suite="SBML_l2v4" name="851" time="0.018"><failure message="sbml_test_suite.cpp(869) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 851))"/></test>
<test suite="SBML_l2v4" name="852" time="0.03"><failure message="sbml_test_suite.cpp(870) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 852))"/></test>
<test suite="SBML_l2v4" name="853" time="0.035"><failure message="sbml_test_suite.cpp(871) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 853))"/></test>
<test suite="SBML_l2v4" name="854" time="0.022"><failure message="sbml_test_suite.cpp(872) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 854))"/></test>
<test suite="SBML_l2v4" name="855" time="0.033"><failure message="sbml_test_suite.cpp(873) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 855))"/></test>
<test suite="SBML_l2v4" name="856" time="0.035"><failure message="sbml_test_suite.cpp(874) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 856))"/></test>
<test suite="SBML_l2v4" name="857" time="0.018"><failure message="sbml_test_suite.cpp(875) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 857))"/></test>
<test suite="SBML_l2v4" name="858" time="0.037"><failure message="sbml_test_suite.cpp(876) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 858))"/></test>
<test suite="SBML_l2v4" name="859" time="0.033"><failure message="sbml_test_suite.cpp(877) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 859))"/></test>
<test suite="SBML_l2v4" name="860" time="0.017"><failure message="sbml_test_suite.cpp(878) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 860))"/></test>
<test suite="SBML_l2v4" name="861" time="0.029"><failure message="sbml_test_suite.cpp(879) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 861))"/></test>
<test suite="SBML_l2v4" name="862" time="0.033"><failure message="sbml_test_suite.cpp(880) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 862))"/></test>
<test suite="SBML_l2v4" name="863" time="0.018"><failure message="sbml_test_suite.cpp(881) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 863))"/></test>
<test suite="SBML_l2v4" name="864" time="0.029"><failure message="sbml_test_suite.cpp(882) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 864))"/></test>
<test suite="SBML_l2v4" name="865" time="0.032"><failure message="sbml_test_suite.cpp(883) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 865))"/></test>
<test suite="SBML_l2v4" name="866" time="0.019"><failure message="sbml_test_suite.cpp(884) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 866))"/></test>
<test suite="SBML_l2v4" name="867" time="0.03"><failure message="sbml_test_suite.cpp(885) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 867))"/></test>
<test suite="SBML_l2v4" name="868" time="0.031"><failure message="sbml_test_suite.cpp(886) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 868))"/></test>
<test suite="SBML_l2v4" name="869" time="0.031"><failure message="sbml_test_suite.cpp(887) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 869))"/></test>
<test suite="SBML_l2v4" name="877" time="0.02"><failure message="sbml_test_suite.cpp(895) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 877))"/></test>
<test suite="SBML_l2v4" name="878" time="0.025"><failure message="sbml_test_suite.cpp(896) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 878))"/></test>
<test suite="SBML_l2v4" name="879" time="0.034"><failure message="sbml_test_suite.cpp(897) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 879))"/></test>
<test suite="SBML_l2v4" name="880" time="0.022"><failure message="sbml_test_suite.cpp(898) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 880))"/></test>
<test suite="SBML_l2v4" name="881" time="0.022"><failure message="sbml_test_suite.cpp(899) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 881))"/></test>
<test suite="SBML_l2v4" name="882" time="0.029"><failure message="sbml_test_suite.cpp(900) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 882))"/></test>
<test suite="SBML_l2v4" name="883" time="0.031"><failure message="sbml_test_suite.cpp(901) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 883))"/></test>
<test suite="SBML_l2v4" name="884" time="0.034"><failure message="sbml_test_suite.cpp(902) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 884))"/></test>
<test suite="SBML_l2v4" name="885" time="0.035"><failure message="sbml_test_suite.cpp(903) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 885))"/></test>
<test suite="SBML_l2v4" name="886" time="0.028"><failure message="sbml_test_suite.cpp(904) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 886))"/></test>
<test suite="SBML_l2v4" name="887" time="0.033"><failure message="sbml_test_suite.cpp(905) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 887))"/></test>
<test suite="SBML_l2v4" name="888" time="0.021"><failure message="sbml_test_suite.cpp(906) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 888))"/></test>
<test suite="SBML_l2v4" name="889" time="0.029"><failure message="sbml_test_suite.cpp(907) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 889))"/></test>
<test suite="SBML_l2v4" name="890" time="0.028"><failure message="sbml_test_suite.cpp(908) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 890))"/></test>
<test suite="SBML_l2v4" name="891" time="0.017"><failure message="sbml_test_suite.cpp(909) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 891))"/></test>
<test suite="SBML_l2v4" name="892" time="0.021"><failure message="sbml_test_suite.cpp(910) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 892))"/></test>
<test suite="SBML_l2v4" name="893" time="0.019"><failure message="sbml_test_suite.cpp(911) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 893))"/></test>
<test suite="SBML_l2v4" name="894" time="0.016"><failure message="sbml_test_suite.cpp(912) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 894))"/></test>
<test suite="SBML_l2v4" name="895" time="0.029"><failure message="sbml_test_suite.cpp(913) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 895))"/></test>
<test suite="SBML_l2v4" name="896" time="0.03"><failure message="sbml_test_suite.cpp(914) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 896))"/></test>
<test suite="SBML_l2v4" name="897" time="0.029"><failure message="sbml_test_suite.cpp(915) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 897))"/></test>
<test suite="SBML_l2v4" name="898" time="0.021"><failure message="sbml_test_suite.cpp(916) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 898))"/></test>
<test suite="SBML_l2v4" name="899" time="0.034"><failure message="sbml_test_suite.cpp(917) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 899))"/></test>
<test suite="SBML_l2v4" name="900" time="0.033"><failure message="sbml_test_suite.cpp(918) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 900))"/></test>
<test suite="SBML_l2v4" name="901" time="0.013"><failure message="sbml_test_suite.cpp(919) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 901))"/></test>
<test suite="SBML_l2v4" name="902" time="0.012"><failure message="sbml_test_suite.cpp(920) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 902))"/></test>
<test suite="SBML_l2v4" name="903" time="0.018"><failure message="sbml_test_suite.cpp(921) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 903))"/></test>
<test suite="SBML_l2v4" name="904" time="0.014"><failure message="sbml_test_suite.cpp(922) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 904))"/></test>
<test suite="SBML_l2v4" name="905" time="0.016"><failure message="sbml_test_suite.cpp(923) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 905))"/></test>
<test suite="SBML_l2v4" name="906" time="0.014"><failure message="sbml_test_suite.cpp(924) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 906))"/></test>
<test suite="SBML_l2v4" name="907" time="0.015"><failure message="sbml_test_suite.cpp(925) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 907))"/></test>
<test suite="SBML_l2v4" name="908" time="0.018"><failure message="sbml_test_suite.cpp(926) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 908))"/></test>
<test suite="SBML_l2v4" name="909" time="0.019"><failure message="sbml_test_suite.cpp(927) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 909))"/></test>
<test suite="SBML_l2v4" name="910" time="0.018"><failure message="sbml_test_suite.cpp(928) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 910))"/></test>
<test suite="SBML_l2v4" name="911" time="0.017"><failure message="sbml_test_suite.cpp(929) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 911))"/></test>
<test suite="SBML_l2v4" name="912" time="0.015"><failure message="sbml_test_suite.cpp(930) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 912))"/></test>
<test suite="SBML_l2v4" name="913" time="0.016"><failure message="sbml_test_suite.cpp(931) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 913))"/></test>
<test suite="SBML_l2v4" name="914" time="0.017"><failure message="sbml_test_suite.cpp(932) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 914))"/></test>
<test suite="SBML_l2v4" name="915" time="0.016"><failure message="sbml_test_suite.cpp(933) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 915))"/></test>
<test suite="SBML_l2v4" name="916" time="0.017"><failure message="sbml_test_suite.cpp(934) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 916))"/></test>
<test suite="SBML_l2v4" name="917" time="0.014"><failure message="sbml_test_suite.cpp(935) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 917))"/></test>
<test suite="SBML_l2v4" name="918" time="0.015"><failure message="sbml_test_suite.cpp(936) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 918))"/></test>
<test suite="SBML_l2v4" name="919" time="0.014"><failure message="sbml_test_suite.cpp(937) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 919))"/></test>
<test suite="SBML_l2v4" name="920" time="0.018"><failure message="sbml_test_suite.cpp(938) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 920))"/></test>
<test suite="SBML_l2v4" name="921" time="0.012"><failure message="sbml_test_suite.cpp(939) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 921))"/></test>
<test suite="SBML_l2v4" name="922" time="0.014"><failure message="sbml_test_suite.cpp(940) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 922))"/></test>
<test suite="SBML_l2v4" name="923" time="0.015"><failure message="sbml_test_suite.cpp(941) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 923))"/></test>
<test suite="SBML_l2v4" name="924" time="0.017"><failure message="sbml_test_suite.cpp(942) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 924))"/></test>
<test suite="SBML_l2v4" name="925" time="0.015"><failure message="sbml_test_suite.cpp(943) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 925))"/></test>
<test suite="SBML_l2v4" name="926" time="0.014"><failure message="sbml_test_suite.cpp(944) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 926))"/></test>
<test suite="SBML_l2v4" name="927" time="0.014"><failure message="sbml_test_suite.cpp(945) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 927))"/></test>
<test suite="SBML_l2v4" name="928" time="0.024"><failure message="sbml_test_suite.cpp(946) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 928))"/></test>
<test suite="SBML_l2v4" name="929" time="0.023"><failure message="sbml_test_suite.cpp(947) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 929))"/></test>
<test suite="SBML_l2v4" name="930" time="0.028"><failure message="sbml_test_suite.cpp(949) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 930))"/></test>
<test suite="SBML_l2v4" name="931" time="0.03"><failure message="sbml_test_suite.cpp(950) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 931))"/></test>
<test suite="SBML_l2v4" name="932" time="0.025"><failure message="sbml_test_suite.cpp(952) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 932))"/></test>
<test suite="SBML_l2v4" name="933" time="0.023"><failure message="sbml_test_suite.cpp(953) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 933))"/></test>
<test suite="SBML_l2v4" name="934" time="0.035"><failure message="sbml_test_suite.cpp(955) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 934))"/></test>
<test suite="SBML_l2v4" name="935" time="0.04"><failure message="sbml_test_suite.cpp(956) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 935))"/></test>
<test suite="SBML_l2v4" name="936" time="0.024"><failure message="sbml_test_suite.cpp(958) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 936))"/></test>
<test suite="SBML_l2v4" name="944" time="0.021"><failure message="sbml_test_suite.cpp(966) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 944))"/></test>
<test suite="SBML_l2v4" name="945" time="0.021"><failure message="sbml_test_suite.cpp(967) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 945))"/></test>
<test suite="SBML_l2v4" name="946" time="0.021"><failure message="sbml_test_suite.cpp(968) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 946))"/></test>
<test suite="SBML_l2v4" name="947" time="0.019"><failure message="sbml_test_suite.cpp(969) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 947))"/></test>
<test suite="SBML_l2v4" name="948" time="0.022"><failure message="sbml_test_suite.cpp(970) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 948))"/></test>
<test suite="SBML_l2v4" name="949" time="0.015"><failure message="sbml_test_suite.cpp(971) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 949))"/></test>
<test suite="SBML_l2v4" name="953" time="0.034"><failure message="sbml_test_suite.cpp(976) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 953))"/></test>
<test suite="SBML_l2v4" name="954" time="0.125"><failure message="sbml_test_suite.cpp(978) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 954))"/></test>
<test suite="SBML_l2v4" name="956" time="0.117"><failure message="sbml_test_suite.cpp(980) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 956))"/></test>
<test suite="SBML_l2v4" name="960" time="0.023"><failure message="sbml_test_suite.cpp(984) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 960))"/></test>
<test suite="SBML_l2v4" name="961" time="0.02"><failure message="sbml_test_suite.cpp(985) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 961))"/></test>
<test suite="SBML_l2v4" name="963" time="0.053"><failure message="sbml_test_suite.cpp(989) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 963))"/></test>
<test suite="SBML_l2v4" name="964" time="0.051"><failure message="sbml_test_suite.cpp(990) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 964))"/></test>
<test suite="SBML_l2v4" name="967" time="0.028"><failure message="sbml_test_suite.cpp(998) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 967))"/></test>
<test suite="SBML_l2v4" name="968" time="0.015"><failure message="sbml_test_suite.cpp(1000) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 968))"/></test>
<test suite="SBML_l2v4" name="969" time="0.016"><failure message="sbml_test_suite.cpp(1001) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 969))"/></test>
<test suite="SBML_l2v4" name="970" time="0.018"><failure message="sbml_test_suite.cpp(1002) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 970))"/></test>
<test suite="SBML_l2v4" name="971" time="0.017"><failure message="sbml_test_suite.cpp(1003) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 971))"/></test>
<test suite="SBML_l2v4" name="972" time="0.021"><failure message="sbml_test_suite.cpp(1004) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 972))"/></test>
<test suite="SBML_l2v4" name="973" time="0.02"><failure message="sbml_test_suite.cpp(1005) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 973))"/></test>
<test suite="SBML_l2v4" name="974" time="0.022"><failure message="sbml_test_suite.cpp(1006) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 974))"/></test>
<test suite="SBML_l2v4" name="975" time="0.028"><failure message="sbml_test_suite.cpp(1007) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 975))"/></test>
<test suite="SBML_l2v4" name="976" time="0.028"><failure message="sbml_test_suite.cpp(1008) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 976))"/></test>
<test suite="SBML_l2v4" name="977" time="0.025"><failure message="sbml_test_suite.cpp(1009) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 977))"/></test>
<test suite="SBML_l2v4" name="979" time="0.023"><failure message="sbml_test_suite.cpp(1011) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 979))"/></test>
<test suite="SBML_l2v4" name="980" time="0.025"><failure message="sbml_test_suite.cpp(1012) : Unhandled exception in CHECK(RunTest(&quot;l2v4&quot;, 980))"/></test>
</unittest-results>
